compilers=&poseidon:&clang
defaultCompiler=clang@LLVM@-poseidon
tools=
demangler=c++filt
objdumper=objdump
supportsBinary=true
needsMulti=false

group.poseidon.compilers=clang@LLVM@-poseidon
group.poseidon.groupName=Clang + Poseidon
group.poseidon.compilerType=clang
group.poseidon.intelAsm=-mllvm --x86-asm-syntax=intel
group.poseidon.supportsExecute=true
group.poseidon.options=-fno-discard-value-names
compiler.clang@LLVM@-poseidon.exe=/opt/compiler-explorer/poseidon/poseidon-ce.sh
compiler.clang@LLVM@-poseidon.name=clang @LLVM@ + Poseidon
compiler.clang@LLVM@-poseidon.semver=@LLVM@
compiler.clang@LLVM@-poseidon.envVars=POSEIDON_CE_CLANG=/usr/bin/clang++-@LLVM@:POSEIDON_CE_ROOT=/opt/compiler-explorer/poseidon

group.clang.compilers=clang@LLVM@
group.clang.groupName=Clang
group.clang.compilerType=clang
group.clang.intelAsm=-mllvm --x86-asm-syntax=intel
group.clang.supportsExecute=true
compiler.clang@LLVM@.exe=/usr/bin/clang++-@LLVM@
compiler.clang@LLVM@.name=clang @LLVM@
compiler.clang@LLVM@.semver=@LLVM@
