compileTimeoutMs=300000
binaryExecTimeoutMs=20000
supportsExecute=true
maxConcurrentCompiles=4
cacheConfig=InMemory(100)
executableCacheConfig=InMemory(100)
compilerCacheConfig=OnDisk(out/compiler-cache,1024)
storageSolution=local
localStorageFolder=./lib/storage/data/
textBanner=Compilation provided by a Poseidon Compiler Explorer
showSponsors=false
thirdPartyIntegrationEnabled=false
statusTrackingEnabled=false
