[package]
name = "enzyme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "enzyme"
path = ".packaging/rust/main.rs"

[dependencies]
bindgen = { version = "0.59", default-features = false, optional = true }
