[check]
# Ignored Rules and justification:
#   S001: line too long - most reasonable maximum line lengths are exceeded by some of the lit run commands
#   C003: 'implicit none' missing 'external' - this is a Fortran 2013 feature and we support older standards
#   C091: external procedure - this is crucial to the way the Fortran bindings are set up
ignore = ["S001", "C003", "C091"]
