// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --cir-flatten-cfg --canonicalize %s | FileCheck %s

!s32i = !cir.int<s, 32>
module {
  cir.func @cond(%arg0: !cir.double) -> !cir.double {
    %0 = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
    %1 = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
    cir.store %arg0, %0 : !cir.double, !cir.ptr<!cir.double>
    cir.scope {
      %3 = cir.load align(8) %0 : !cir.ptr<!cir.double>, !cir.double
      %4 = cir.const #cir.int<0> : !s32i
      %5 = cir.cast int_to_float %4 : !s32i -> !cir.double
      %6 = cir.cmp gt %3, %5 : !cir.double
      cir.if %6 {
        %7 = cir.load align(8) %0 : !cir.ptr<!cir.double>, !cir.double
        %8 = cir.fmul %7, %7 : !cir.double
        cir.store %8, %1 : !cir.double, !cir.ptr<!cir.double>
        %9 = cir.load %1 : !cir.ptr<!cir.double>, !cir.double
        cir.return %9 : !cir.double
      } else {
        %7 = cir.load align(8) %0 : !cir.ptr<!cir.double>, !cir.double
        %8 = cir.fneg %7 : !cir.double
        cir.store %8, %1 : !cir.double, !cir.ptr<!cir.double>
        %9 = cir.load %1 : !cir.ptr<!cir.double>, !cir.double
        cir.return %9 : !cir.double
      }
    }
    %2 = cir.load %1 : !cir.ptr<!cir.double>, !cir.double
    cir.return %2 : !cir.double
  }
}

// CHECK-LABEL:   cir.func @cond(
// CHECK-SAME:                   %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double) -> !cir.double {
// CHECK:           %[[CONST_0:.*]] = cir.const #cir.int<0> : !s32i
// CHECK:           %[[ALLOCA_0:.*]] = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_1:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG0]], %[[ALLOCA_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_0:.*]] = cir.load align(8) %[[ALLOCA_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[CAST_0:.*]] = cir.cast int_to_float %[[CONST_0]] : !s32i -> !cir.double
// CHECK:           %[[CMP_0:.*]] = cir.cmp gt %[[LOAD_0]], %[[CAST_0]] : !cir.double
// CHECK:           cir.brcond %[[CMP_0]] ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           %[[LOAD_1:.*]] = cir.load align(8) %[[ALLOCA_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[LOAD_1]], %[[LOAD_1]] : !cir.double
// CHECK:           cir.store %[[FMUL_0]], %[[ALLOCA_1]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_2:.*]] = cir.load %[[ALLOCA_1]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           cir.return %[[LOAD_2]] : !cir.double
// CHECK:         ^bb2:
// CHECK:           %[[LOAD_3:.*]] = cir.load align(8) %[[ALLOCA_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FNEG_0:.*]] = cir.fneg %[[LOAD_3]] : !cir.double
// CHECK:           cir.store %[[FNEG_0]], %[[ALLOCA_1]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_4:.*]] = cir.load %[[ALLOCA_1]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           cir.return %[[LOAD_4]] : !cir.double
// CHECK:         }
