// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize %s | FileCheck %s

// Flattened output of clang -fclangir -emit-cir -O0 -fno-math-errno for
//   struct P { double x, y; };
//   double norm2(struct P p) { return p.x * p.x + p.y * p.y; }

!rec_P = !cir.struct<"P" {data !cir.double, data !cir.double}>
!rec_anon_struct = !cir.struct<{data !cir.double, data !cir.double}>
module {
  cir.func @norm2(%arg0: !cir.double, %arg1: !cir.double) -> !cir.double {
    %0 = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
    %1 = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
    %2 = cir.get_member %1[0] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
    cir.store %arg0, %2 : !cir.double, !cir.ptr<!cir.double>
    %3 = cir.get_member %1[1] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
    cir.store %arg1, %3 : !cir.double, !cir.ptr<!cir.double>
    %4 = cir.load %1 : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
    cir.store %4, %0 : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
    %5 = cir.cast bitcast %0 : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!rec_P>
    %6 = cir.load %5 : !cir.ptr<!rec_P>, !rec_P
    %7 = cir.alloca "p" align(8) init : !cir.ptr<!rec_P>
    %8 = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
    cir.store %6, %7 : !rec_P, !cir.ptr<!rec_P>
    %9 = cir.get_member %7[0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
    %10 = cir.load align(8) %9 : !cir.ptr<!cir.double>, !cir.double
    %11 = cir.get_member %7[0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
    %12 = cir.load align(8) %11 : !cir.ptr<!cir.double>, !cir.double
    %13 = cir.get_member %7[1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
    %14 = cir.load align(8) %13 : !cir.ptr<!cir.double>, !cir.double
    %15 = cir.get_member %7[1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
    %16 = cir.load align(8) %15 : !cir.ptr<!cir.double>, !cir.double
    %17 = cir.fmul %14, %16 : !cir.double
    %18 = cir.fmuladd %10, %12, %17 : !cir.double
    cir.store %18, %8 : !cir.double, !cir.ptr<!cir.double>
    %19 = cir.load %8 : !cir.ptr<!cir.double>, !cir.double
    cir.return %19 : !cir.double
  }
  cir.func @dnorm2(%x: !cir.double, %dx: !cir.double, %y: !cir.double, %dy: !cir.double) -> !cir.double {
    %r = enzyme.fwddiff @norm2(%x, %dx, %y, %dy) { activity=[#enzyme.activity<enzyme_dup>, #enzyme.activity<enzyme_dup>], ret_activity=[#enzyme.activity<enzyme_dupnoneed>] } : (!cir.double, !cir.double, !cir.double, !cir.double) -> !cir.double
    cir.return %r : !cir.double
  }
}

// CHECK-LABEL:   cir.func private @fwddiffenorm2(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG2:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG3:[a-zA-Z0-9$._-]+]]: !cir.double) -> !cir.double {
// CHECK:           %[[ALLOCA_0:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           %[[ALLOCA_1:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           %[[ALLOCA_2:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           %[[ALLOCA_3:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           %[[GET_MEMBER_0:.*]] = cir.get_member %[[ALLOCA_2]][0] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_1:.*]] = cir.get_member %[[ALLOCA_3]][0] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG1]], %[[GET_MEMBER_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG0]], %[[GET_MEMBER_1]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_2:.*]] = cir.get_member %[[ALLOCA_2]][1] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_3:.*]] = cir.get_member %[[ALLOCA_3]][1] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG3]], %[[GET_MEMBER_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG2]], %[[GET_MEMBER_3]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_0:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
// CHECK:           %[[LOAD_1:.*]] = cir.load %[[ALLOCA_3]] : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
// CHECK:           cir.store %[[LOAD_0]], %[[ALLOCA_0]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           cir.store %[[LOAD_1]], %[[ALLOCA_1]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           %[[CAST_0:.*]] = cir.cast bitcast %[[ALLOCA_0]] : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!rec_P>
// CHECK:           %[[CAST_1:.*]] = cir.cast bitcast %[[ALLOCA_1]] : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!rec_P>
// CHECK:           %[[LOAD_2:.*]] = cir.load %[[CAST_0]] : !cir.ptr<!rec_P>, !rec_P
// CHECK:           %[[LOAD_3:.*]] = cir.load %[[CAST_1]] : !cir.ptr<!rec_P>, !rec_P
// CHECK:           %[[ALLOCA_4:.*]] = cir.alloca "p" align(8) init : !cir.ptr<!rec_P>
// CHECK:           %[[ALLOCA_5:.*]] = cir.alloca "p" align(8) init : !cir.ptr<!rec_P>
// CHECK:           %[[ALLOCA_6:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_7:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[LOAD_2]], %[[ALLOCA_4]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           cir.store %[[LOAD_3]], %[[ALLOCA_5]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           %[[GET_MEMBER_4:.*]] = cir.get_member %[[ALLOCA_4]][0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_5:.*]] = cir.get_member %[[ALLOCA_5]][0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_4:.*]] = cir.load align(8) %[[GET_MEMBER_4]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_5:.*]] = cir.load align(8) %[[GET_MEMBER_5]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[GET_MEMBER_6:.*]] = cir.get_member %[[ALLOCA_4]][0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_7:.*]] = cir.get_member %[[ALLOCA_5]][0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_6:.*]] = cir.load align(8) %[[GET_MEMBER_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_7:.*]] = cir.load align(8) %[[GET_MEMBER_7]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[GET_MEMBER_8:.*]] = cir.get_member %[[ALLOCA_4]][1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_9:.*]] = cir.get_member %[[ALLOCA_5]][1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_8:.*]] = cir.load align(8) %[[GET_MEMBER_8]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_9:.*]] = cir.load align(8) %[[GET_MEMBER_9]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[GET_MEMBER_10:.*]] = cir.get_member %[[ALLOCA_4]][1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_11:.*]] = cir.get_member %[[ALLOCA_5]][1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_10:.*]] = cir.load align(8) %[[GET_MEMBER_10]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_11:.*]] = cir.load align(8) %[[GET_MEMBER_11]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[LOAD_8]], %[[LOAD_11]] : !cir.double
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[LOAD_10]], %[[LOAD_9]] : !cir.double
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[FMUL_0]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[FMUL_2:.*]] = cir.fmul %[[LOAD_9]], %[[LOAD_11]] : !cir.double
// CHECK:           %[[FMUL_3:.*]] = cir.fmul %[[LOAD_4]], %[[LOAD_7]] : !cir.double
// CHECK:           %[[FMUL_4:.*]] = cir.fmul %[[LOAD_6]], %[[LOAD_5]] : !cir.double
// CHECK:           %[[FADD_1:.*]] = cir.fadd %[[FMUL_3]], %[[FMUL_4]] : !cir.double
// CHECK:           %[[FADD_2:.*]] = cir.fadd %[[FADD_1]], %[[FADD_0]] : !cir.double
// CHECK:           %[[FMULADD_0:.*]] = cir.fmuladd %[[LOAD_5]], %[[LOAD_7]], %[[FMUL_2]] : !cir.double
// CHECK:           cir.store %[[FADD_2]], %[[ALLOCA_6]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[FMULADD_0]], %[[ALLOCA_7]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_12:.*]] = cir.load %[[ALLOCA_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           cir.return %[[LOAD_12]] : !cir.double
// CHECK:         }
