// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize %s | FileCheck %s

// Flattened output of clang -fclangir -emit-cir -O0 -fno-math-errno for
//   double loop(double *a, int n) { double s = 0; for (int i = 0; i < n; i++) s += a[i] * a[i]; return s; }

!s32i = !cir.int<s, 32>
!s64i = !cir.int<s, 64>
module {
  cir.func @loop(%arg0: !cir.ptr<!cir.double> , %arg1: !s32i ) -> !cir.double {
    %0 = cir.const #cir.int<0> : !s32i
    %1 = cir.alloca "a" align(8) init : !cir.ptr<!cir.ptr<!cir.double>>
    %2 = cir.alloca "n" align(4) init : !cir.ptr<!s32i>
    %3 = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
    %4 = cir.alloca "s" align(8) init : !cir.ptr<!cir.double>
    cir.store %arg0, %1 : !cir.ptr<!cir.double>, !cir.ptr<!cir.ptr<!cir.double>>
    cir.store %arg1, %2 : !s32i, !cir.ptr<!s32i>
    %5 = cir.cast int_to_float %0 : !s32i -> !cir.double
    cir.store align(8) %5, %4 : !cir.double, !cir.ptr<!cir.double>
    %6 = cir.alloca "i" align(4) init : !cir.ptr<!s32i>
    cir.store align(4) %0, %6 : !s32i, !cir.ptr<!s32i>
    cir.br ^bb1
  ^bb1:  // 2 preds: ^bb0, ^bb2
    %7 = cir.load align(4) %6 : !cir.ptr<!s32i>, !s32i
    %8 = cir.load align(4) %2 : !cir.ptr<!s32i>, !s32i
    %9 = cir.cmp lt %7, %8 : !s32i
    cir.brcond %9 ^bb2, ^bb3
  ^bb2:  // pred: ^bb1
    %10 = cir.load align(4) %6 : !cir.ptr<!s32i>, !s32i
    %11 = cir.cast integral %10 : !s32i -> !s64i
    %12 = cir.load align(8) %1 : !cir.ptr<!cir.ptr<!cir.double>>, !cir.ptr<!cir.double>
    %13 = cir.ptr_stride %12, %11 : (!cir.ptr<!cir.double>, !s64i) -> !cir.ptr<!cir.double>
    %14 = cir.load align(8) %13 : !cir.ptr<!cir.double>, !cir.double
    %15 = cir.load align(4) %6 : !cir.ptr<!s32i>, !s32i
    %16 = cir.cast integral %15 : !s32i -> !s64i
    %17 = cir.load align(8) %1 : !cir.ptr<!cir.ptr<!cir.double>>, !cir.ptr<!cir.double>
    %18 = cir.ptr_stride %17, %16 : (!cir.ptr<!cir.double>, !s64i) -> !cir.ptr<!cir.double>
    %19 = cir.load align(8) %18 : !cir.ptr<!cir.double>, !cir.double
    %20 = cir.load align(8) %4 : !cir.ptr<!cir.double>, !cir.double
    %21 = cir.fmuladd %14, %19, %20 : !cir.double
    cir.store align(8) %21, %4 : !cir.double, !cir.ptr<!cir.double>
    %22 = cir.load align(4) %6 : !cir.ptr<!s32i>, !s32i
    %23 = cir.inc nsw %22 : !s32i
    cir.store align(4) %23, %6 : !s32i, !cir.ptr<!s32i>
    cir.br ^bb1
  ^bb3:  // pred: ^bb1
    %24 = cir.load align(8) %4 : !cir.ptr<!cir.double>, !cir.double
    cir.store %24, %3 : !cir.double, !cir.ptr<!cir.double>
    %25 = cir.load %3 : !cir.ptr<!cir.double>, !cir.double
    cir.return %25 : !cir.double
  }
  cir.func @dloop(%a: !cir.ptr<!cir.double>, %da: !cir.ptr<!cir.double>, %n: !s32i) -> !cir.double {
    %r = enzyme.fwddiff @loop(%a, %da, %n) { activity=[#enzyme.activity<enzyme_dup>, #enzyme.activity<enzyme_const>], ret_activity=[#enzyme.activity<enzyme_dupnoneed>] } : (!cir.ptr<!cir.double>, !cir.ptr<!cir.double>, !s32i) -> !cir.double
    cir.return %r : !cir.double
  }
}

// CHECK-LABEL:   cir.func private @fwddiffeloop(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.ptr<!cir.double>,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.ptr<!cir.double>,
// CHECK-SAME:      %[[ARG2:[a-zA-Z0-9$._-]+]]: !s32i) -> !cir.double {
// CHECK:           %[[CONST_0:.*]] = cir.const #cir.fp<0.000000e+00> : !cir.double
// CHECK:           %[[CONST_1:.*]] = cir.const #cir.int<0> : !s32i
// CHECK:           %[[ALLOCA_0:.*]] = cir.alloca "a" align(8) init : !cir.ptr<!cir.ptr<!cir.double>>
// CHECK:           %[[ALLOCA_1:.*]] = cir.alloca "a" align(8) init : !cir.ptr<!cir.ptr<!cir.double>>
// CHECK:           %[[ALLOCA_2:.*]] = cir.alloca "n" align(4) init : !cir.ptr<!s32i>
// CHECK:           %[[ALLOCA_3:.*]] = cir.alloca "n" align(4) init : !cir.ptr<!s32i>
// CHECK:           %[[ALLOCA_4:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_5:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_6:.*]] = cir.alloca "s" align(8) init : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_7:.*]] = cir.alloca "s" align(8) init : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG1]], %[[ALLOCA_0]] : !cir.ptr<!cir.double>, !cir.ptr<!cir.ptr<!cir.double>>
// CHECK:           cir.store %[[ARG0]], %[[ALLOCA_1]] : !cir.ptr<!cir.double>, !cir.ptr<!cir.ptr<!cir.double>>
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_2]] : !s32i, !cir.ptr<!s32i>
// CHECK:           cir.store %[[ARG2]], %[[ALLOCA_3]] : !s32i, !cir.ptr<!s32i>
// CHECK:           %[[CAST_0:.*]] = cir.cast int_to_float %[[CONST_1]] : !s32i -> !cir.double
// CHECK:           cir.store align(8) %[[CONST_0]], %[[ALLOCA_6]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store align(8) %[[CAST_0]], %[[ALLOCA_7]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_8:.*]] = cir.alloca "i" align(4) init : !cir.ptr<!s32i>
// CHECK:           %[[ALLOCA_9:.*]] = cir.alloca "i" align(4) init : !cir.ptr<!s32i>
// CHECK:           cir.store align(4) %[[CONST_1]], %[[ALLOCA_8]] : !s32i, !cir.ptr<!s32i>
// CHECK:           cir.store align(4) %[[CONST_1]], %[[ALLOCA_9]] : !s32i, !cir.ptr<!s32i>
// CHECK:           cir.br ^bb1
// CHECK:         ^bb1:
// CHECK:           %[[LOAD_0:.*]] = cir.load align(4) %[[ALLOCA_9]] : !cir.ptr<!s32i>, !s32i
// CHECK:           %[[LOAD_1:.*]] = cir.load align(4) %[[ALLOCA_3]] : !cir.ptr<!s32i>, !s32i
// CHECK:           %[[CMP_0:.*]] = cir.cmp lt %[[LOAD_0]], %[[LOAD_1]] : !s32i
// CHECK:           cir.brcond %[[CMP_0]] ^bb2, ^bb3
// CHECK:         ^bb2:
// CHECK:           %[[LOAD_2:.*]] = cir.load align(4) %[[ALLOCA_9]] : !cir.ptr<!s32i>, !s32i
// CHECK:           %[[CAST_1:.*]] = cir.cast integral %[[LOAD_2]] : !s32i -> !s64i
// CHECK:           %[[LOAD_3:.*]] = cir.load align(8) %[[ALLOCA_0]] : !cir.ptr<!cir.ptr<!cir.double>>, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_4:.*]] = cir.load align(8) %[[ALLOCA_1]] : !cir.ptr<!cir.ptr<!cir.double>>, !cir.ptr<!cir.double>
// CHECK:           %[[PTR_STRIDE_0:.*]] = cir.ptr_stride %[[LOAD_3]], %[[CAST_1]] : (!cir.ptr<!cir.double>, !s64i) -> !cir.ptr<!cir.double>
// CHECK:           %[[PTR_STRIDE_1:.*]] = cir.ptr_stride %[[LOAD_4]], %[[CAST_1]] : (!cir.ptr<!cir.double>, !s64i) -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_5:.*]] = cir.load align(8) %[[PTR_STRIDE_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_6:.*]] = cir.load align(8) %[[PTR_STRIDE_1]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_7:.*]] = cir.load align(4) %[[ALLOCA_9]] : !cir.ptr<!s32i>, !s32i
// CHECK:           %[[CAST_2:.*]] = cir.cast integral %[[LOAD_7]] : !s32i -> !s64i
// CHECK:           %[[LOAD_8:.*]] = cir.load align(8) %[[ALLOCA_0]] : !cir.ptr<!cir.ptr<!cir.double>>, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_9:.*]] = cir.load align(8) %[[ALLOCA_1]] : !cir.ptr<!cir.ptr<!cir.double>>, !cir.ptr<!cir.double>
// CHECK:           %[[PTR_STRIDE_2:.*]] = cir.ptr_stride %[[LOAD_8]], %[[CAST_2]] : (!cir.ptr<!cir.double>, !s64i) -> !cir.ptr<!cir.double>
// CHECK:           %[[PTR_STRIDE_3:.*]] = cir.ptr_stride %[[LOAD_9]], %[[CAST_2]] : (!cir.ptr<!cir.double>, !s64i) -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_10:.*]] = cir.load align(8) %[[PTR_STRIDE_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_11:.*]] = cir.load align(8) %[[PTR_STRIDE_3]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_12:.*]] = cir.load align(8) %[[ALLOCA_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_13:.*]] = cir.load align(8) %[[ALLOCA_7]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[LOAD_5]], %[[LOAD_11]] : !cir.double
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[LOAD_10]], %[[LOAD_6]] : !cir.double
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[FMUL_0]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[FADD_1:.*]] = cir.fadd %[[FADD_0]], %[[LOAD_12]] : !cir.double
// CHECK:           %[[FMULADD_0:.*]] = cir.fmuladd %[[LOAD_6]], %[[LOAD_11]], %[[LOAD_13]] : !cir.double
// CHECK:           cir.store align(8) %[[FADD_1]], %[[ALLOCA_6]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store align(8) %[[FMULADD_0]], %[[ALLOCA_7]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_14:.*]] = cir.load align(4) %[[ALLOCA_9]] : !cir.ptr<!s32i>, !s32i
// CHECK:           %[[INC_0:.*]] = cir.inc %[[LOAD_14]] : !s32i
// CHECK:           cir.store align(4) %[[CONST_1]], %[[ALLOCA_8]] : !s32i, !cir.ptr<!s32i>
// CHECK:           cir.store align(4) %[[INC_0]], %[[ALLOCA_9]] : !s32i, !cir.ptr<!s32i>
// CHECK:           cir.br ^bb1
// CHECK:         ^bb3:
// CHECK:           %[[LOAD_15:.*]] = cir.load align(8) %[[ALLOCA_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_16:.*]] = cir.load align(8) %[[ALLOCA_7]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           cir.store %[[LOAD_15]], %[[ALLOCA_4]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[LOAD_16]], %[[ALLOCA_5]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_17:.*]] = cir.load %[[ALLOCA_4]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           cir.return %[[LOAD_17]] : !cir.double
// CHECK:         }
