// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme %s | FileCheck %s

// Tests rules that build constants (CirCF0, CirCF1), cir.cmp and
// cir.select.

// d/dx: dx * (y * pow(x, y - 1))
// d/dy: dy * (x == 0 ? 0 : pow(x, y) * log(x))

module {
  cir.func @f(%x: !cir.double, %y: !cir.double) -> !cir.double {
    %0 = cir.pow %x, %y : !cir.double
    cir.return %0 : !cir.double
  }
  cir.func @df(%x: !cir.double, %dx: !cir.double, %y: !cir.double, %dy: !cir.double) -> !cir.double {
    %r = enzyme.fwddiff @f(%x, %dx, %y, %dy) { activity=[#enzyme.activity<enzyme_dup>, #enzyme.activity<enzyme_dup>], ret_activity=[#enzyme.activity<enzyme_dupnoneed>] } : (!cir.double, !cir.double, !cir.double, !cir.double) -> !cir.double
    cir.return %r : !cir.double
  }
}

// CHECK-LABEL:   cir.func private @fwddiffef(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG2:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG3:[a-zA-Z0-9$._-]+]]: !cir.double) -> !cir.double {
// CHECK:           %[[CONST_0:.*]] = cir.const #cir.fp<1.000000e+00> : !cir.double
// CHECK:           %[[FSUB_0:.*]] = cir.fsub %[[ARG2]], %[[CONST_0]] : !cir.double
// CHECK:           %[[POW_0:.*]] = cir.pow %[[ARG0]], %[[FSUB_0]] : !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[ARG2]], %[[POW_0]] : !cir.double
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[ARG1]], %[[FMUL_0]] : !cir.double
// CHECK:           %[[CONST_1:.*]] = cir.const #cir.fp<0.000000e+00> : !cir.double
// CHECK:           %[[CMP_0:.*]] = cir.cmp eq %[[ARG0]], %[[CONST_1]] : !cir.double
// CHECK:           %[[POW_1:.*]] = cir.pow %[[ARG0]], %[[ARG2]] : !cir.double
// CHECK:           %[[LOG_0:.*]] = cir.log %[[ARG0]] : !cir.double
// CHECK:           %[[FMUL_2:.*]] = cir.fmul %[[POW_1]], %[[LOG_0]] : !cir.double
// CHECK:           %[[SELECT_0:.*]] = cir.select if %[[CMP_0]] then %[[CONST_1]] else %[[FMUL_2]] : (!cir.bool, !cir.double, !cir.double) -> !cir.double
// CHECK:           %[[FMUL_3:.*]] = cir.fmul %[[ARG3]], %[[SELECT_0]] : !cir.double
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[FMUL_1]], %[[FMUL_3]] : !cir.double
// CHECK:           %[[POW_2:.*]] = cir.pow %[[ARG0]], %[[ARG2]] : !cir.double
// CHECK:           cir.return %[[FADD_0]] : !cir.double
// CHECK:         }
