// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme %s | FileCheck %s


// Desired: ydx + xdy
module {
  cir.func @f(%x: !cir.double, %y: !cir.double) -> !cir.double {
    %0 = cir.fmul %x, %y : !cir.double
    cir.return %0 : !cir.double
  }
  cir.func @df(%x: !cir.double, %dx: !cir.double, %y: !cir.double, %dy: !cir.double) -> !cir.double {
    %r = enzyme.fwddiff @f(%x, %dx, %y, %dy) { activity=[#enzyme.activity<enzyme_dup>, #enzyme.activity<enzyme_dup>], ret_activity=[#enzyme.activity<enzyme_dupnoneed>] } : (!cir.double, !cir.double, !cir.double, !cir.double) -> !cir.double
    cir.return %r : !cir.double
  }
}

// CHECK-LABEL:   cir.func private @fwddiffef(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG2:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG3:[a-zA-Z0-9$._-]+]]: !cir.double) -> !cir.double {
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[ARG1]], %[[ARG2]] : !cir.double
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[ARG3]], %[[ARG0]] : !cir.double
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[FMUL_0]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[FMUL_2:.*]] = cir.fmul %[[ARG0]], %[[ARG2]] : !cir.double
// CHECK:           cir.return %[[FADD_0]] : !cir.double
// CHECK:         }
