// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize %s | FileCheck %s

// Flattened output of clang -fclangir -emit-cir -O0 -fno-math-errno for
//   float castf(float x) { double d = x; return (float)(d * d); }

module {
  cir.func @castf(%arg0: !cir.float ) -> !cir.float {
    %0 = cir.alloca "x" align(4) init : !cir.ptr<!cir.float>
    %1 = cir.alloca "__retval" align(4) : !cir.ptr<!cir.float>
    %2 = cir.alloca "d" align(8) init : !cir.ptr<!cir.double>
    cir.store %arg0, %0 : !cir.float, !cir.ptr<!cir.float>
    %3 = cir.load align(4) %0 : !cir.ptr<!cir.float>, !cir.float
    %4 = cir.cast floating %3 : !cir.float -> !cir.double
    cir.store align(8) %4, %2 : !cir.double, !cir.ptr<!cir.double>
    %5 = cir.load align(8) %2 : !cir.ptr<!cir.double>, !cir.double
    %6 = cir.load align(8) %2 : !cir.ptr<!cir.double>, !cir.double
    %7 = cir.fmul %5, %6 : !cir.double
    %8 = cir.cast floating %7 : !cir.double -> !cir.float
    cir.store %8, %1 : !cir.float, !cir.ptr<!cir.float>
    %9 = cir.load %1 : !cir.ptr<!cir.float>, !cir.float
    cir.return %9 : !cir.float
  }
  cir.func @dcastf(%x: !cir.float, %dx: !cir.float) -> !cir.float {
    %r = enzyme.fwddiff @castf(%x, %dx) { activity=[#enzyme.activity<enzyme_dup>], ret_activity=[#enzyme.activity<enzyme_dupnoneed>] } : (!cir.float, !cir.float) -> !cir.float
    cir.return %r : !cir.float
  }
}

// CHECK-LABEL:   cir.func private @fwddiffecastf(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.float,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.float) -> !cir.float {
// CHECK:           %[[ALLOCA_0:.*]] = cir.alloca "x" align(4) init : !cir.ptr<!cir.float>
// CHECK:           %[[ALLOCA_1:.*]] = cir.alloca "x" align(4) init : !cir.ptr<!cir.float>
// CHECK:           %[[ALLOCA_2:.*]] = cir.alloca "__retval" align(4) : !cir.ptr<!cir.float>
// CHECK:           %[[ALLOCA_3:.*]] = cir.alloca "__retval" align(4) : !cir.ptr<!cir.float>
// CHECK:           %[[ALLOCA_4:.*]] = cir.alloca "d" align(8) init : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_5:.*]] = cir.alloca "d" align(8) init : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG1]], %[[ALLOCA_0]] : !cir.float, !cir.ptr<!cir.float>
// CHECK:           cir.store %[[ARG0]], %[[ALLOCA_1]] : !cir.float, !cir.ptr<!cir.float>
// CHECK:           %[[LOAD_0:.*]] = cir.load align(4) %[[ALLOCA_0]] : !cir.ptr<!cir.float>, !cir.float
// CHECK:           %[[LOAD_1:.*]] = cir.load align(4) %[[ALLOCA_1]] : !cir.ptr<!cir.float>, !cir.float
// CHECK:           %[[CAST_0:.*]] = cir.cast floating %[[LOAD_0]] : !cir.float -> !cir.double
// CHECK:           %[[CAST_1:.*]] = cir.cast floating %[[LOAD_1]] : !cir.float -> !cir.double
// CHECK:           cir.store align(8) %[[CAST_0]], %[[ALLOCA_4]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store align(8) %[[CAST_1]], %[[ALLOCA_5]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_2:.*]] = cir.load align(8) %[[ALLOCA_4]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_3:.*]] = cir.load align(8) %[[ALLOCA_5]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_4:.*]] = cir.load align(8) %[[ALLOCA_4]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_5:.*]] = cir.load align(8) %[[ALLOCA_5]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[LOAD_2]], %[[LOAD_5]] : !cir.double
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[LOAD_4]], %[[LOAD_3]] : !cir.double
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[FMUL_0]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[FMUL_2:.*]] = cir.fmul %[[LOAD_3]], %[[LOAD_5]] : !cir.double
// CHECK:           %[[CAST_2:.*]] = cir.cast floating %[[FADD_0]] : !cir.double -> !cir.float
// CHECK:           %[[CAST_3:.*]] = cir.cast floating %[[FMUL_2]] : !cir.double -> !cir.float
// CHECK:           cir.store %[[CAST_2]], %[[ALLOCA_2]] : !cir.float, !cir.ptr<!cir.float>
// CHECK:           cir.store %[[CAST_3]], %[[ALLOCA_3]] : !cir.float, !cir.ptr<!cir.float>
// CHECK:           %[[LOAD_6:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!cir.float>, !cir.float
// CHECK:           cir.return %[[LOAD_6]] : !cir.float
// CHECK:         }
