// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize %s | FileCheck %s

// Flattened output of clang -fclangir -emit-cir -O0 -fno-math-errno for
//   double cond(double x) { if (x > 0) return x * x; else return -x; }

!s32i = !cir.int<s, 32>
module {
  cir.func @cond(%arg0: !cir.double ) -> !cir.double {
    %0 = cir.const #cir.int<0> : !s32i
    %1 = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
    %2 = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
    cir.store %arg0, %1 : !cir.double, !cir.ptr<!cir.double>
    %3 = cir.load align(8) %1 : !cir.ptr<!cir.double>, !cir.double
    %4 = cir.cast int_to_float %0 : !s32i -> !cir.double
    %5 = cir.cmp gt %3, %4 : !cir.double
    cir.brcond %5 ^bb1, ^bb2
  ^bb1:  // pred: ^bb0
    %6 = cir.load align(8) %1 : !cir.ptr<!cir.double>, !cir.double
    %7 = cir.load align(8) %1 : !cir.ptr<!cir.double>, !cir.double
    %8 = cir.fmul %6, %7 : !cir.double
    cir.store %8, %2 : !cir.double, !cir.ptr<!cir.double>
    %9 = cir.load %2 : !cir.ptr<!cir.double>, !cir.double
    cir.return %9 : !cir.double
  ^bb2:  // pred: ^bb0
    %10 = cir.load align(8) %1 : !cir.ptr<!cir.double>, !cir.double
    %11 = cir.fneg %10 : !cir.double
    cir.store %11, %2 : !cir.double, !cir.ptr<!cir.double>
    %12 = cir.load %2 : !cir.ptr<!cir.double>, !cir.double
    cir.return %12 : !cir.double
  }
  cir.func @dcond(%x: !cir.double, %dx: !cir.double) -> !cir.double {
    %r = enzyme.fwddiff @cond(%x, %dx) { activity=[#enzyme.activity<enzyme_dup>], ret_activity=[#enzyme.activity<enzyme_dupnoneed>] } : (!cir.double, !cir.double) -> !cir.double
    cir.return %r : !cir.double
  }
}

// CHECK-LABEL:   cir.func private @fwddiffecond(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.double) -> !cir.double {
// CHECK:           %[[CONST_0:.*]] = cir.const #cir.int<0> : !s32i
// CHECK:           %[[ALLOCA_0:.*]] = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_1:.*]] = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_2:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_3:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG1]], %[[ALLOCA_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG0]], %[[ALLOCA_1]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_0:.*]] = cir.load align(8) %[[ALLOCA_1]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[CAST_0:.*]] = cir.cast int_to_float %[[CONST_0]] : !s32i -> !cir.double
// CHECK:           %[[CMP_0:.*]] = cir.cmp gt %[[LOAD_0]], %[[CAST_0]] : !cir.double
// CHECK:           cir.brcond %[[CMP_0]] ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           %[[LOAD_1:.*]] = cir.load align(8) %[[ALLOCA_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_2:.*]] = cir.load align(8) %[[ALLOCA_1]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_3:.*]] = cir.load align(8) %[[ALLOCA_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_4:.*]] = cir.load align(8) %[[ALLOCA_1]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[LOAD_1]], %[[LOAD_4]] : !cir.double
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[LOAD_3]], %[[LOAD_2]] : !cir.double
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[FMUL_0]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[FMUL_2:.*]] = cir.fmul %[[LOAD_2]], %[[LOAD_4]] : !cir.double
// CHECK:           cir.store %[[FADD_0]], %[[ALLOCA_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[FMUL_2]], %[[ALLOCA_3]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_5:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           cir.return %[[LOAD_5]] : !cir.double
// CHECK:         ^bb2:
// CHECK:           %[[LOAD_6:.*]] = cir.load align(8) %[[ALLOCA_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_7:.*]] = cir.load align(8) %[[ALLOCA_1]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FNEG_0:.*]] = cir.fneg %[[LOAD_6]] : !cir.double
// CHECK:           %[[FNEG_1:.*]] = cir.fneg %[[LOAD_7]] : !cir.double
// CHECK:           cir.store %[[FNEG_0]], %[[ALLOCA_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[FNEG_1]], %[[ALLOCA_3]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_8:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           cir.return %[[LOAD_8]] : !cir.double
// CHECK:         }
