// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize %s | FileCheck %s

!rec = !cir.struct<{data !cir.double, data !cir.double}>
module {
  cir.func @f(%x: !cir.double, %y: !cir.double) -> !cir.double {
    %0 = cir.fmul %x, %y : !cir.double
    cir.return %0 : !cir.double
  }
  cir.func @df(%x: !cir.double, %dx: !cir.double, %y: !cir.double, %dy: !cir.double) -> !cir.double {
    %res = enzyme.fwddiff @f(%x, %dx, %y, %dy) { activity=[#enzyme.activity<enzyme_dup>, #enzyme.activity<enzyme_dup>], ret_activity=[#enzyme.activity<enzyme_dup>] } : (!cir.double, !cir.double, !cir.double, !cir.double) -> !rec
    %p = cir.extract_member %res[0] : !rec -> !cir.double
    %t = cir.extract_member %res[1] : !rec -> !cir.double
    %s = cir.fadd %p, %t : !cir.double
    cir.return %s : !cir.double
  }
}

// CHECK-LABEL:   cir.func private @fwddiffef(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG2:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG3:[a-zA-Z0-9$._-]+]]: !cir.double) -> !rec_anon_struct {
// CHECK:           %[[CONST_0:.*]] = cir.const #cir.zero : !rec_anon_struct
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[ARG1]], %[[ARG2]] : !cir.double
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[ARG3]], %[[ARG0]] : !cir.double
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[FMUL_0]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[FMUL_2:.*]] = cir.fmul %[[ARG0]], %[[ARG2]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_0:.*]] = cir.insert_member %[[CONST_0]][0], %[[FMUL_2]] : !rec_anon_struct, !cir.double
// CHECK:           %[[INSERT_MEMBER_1:.*]] = cir.insert_member %[[INSERT_MEMBER_0]][1], %[[FADD_0]] : !rec_anon_struct, !cir.double
// CHECK:           cir.return %[[INSERT_MEMBER_1]] : !rec_anon_struct
// CHECK:         }
