// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize %s | FileCheck %s

// Flattened output of clang -fclangir -emit-cir -O0 -fno-math-errno for
//   struct P { double x, y; };
//   double assign(struct P p) { struct P q = p; return q.x * q.y; }

!rec_P = !cir.struct<"P" {data !cir.double, data !cir.double}>
!rec_anon_struct = !cir.struct<{data !cir.double, data !cir.double}>
module {
  cir.func @assign(%arg0: !cir.double, %arg1: !cir.double) -> !cir.double {
    %0 = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
    %1 = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
    %2 = cir.get_member %1[0] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
    cir.store %arg0, %2 : !cir.double, !cir.ptr<!cir.double>
    %3 = cir.get_member %1[1] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
    cir.store %arg1, %3 : !cir.double, !cir.ptr<!cir.double>
    %4 = cir.load %1 : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
    cir.store %4, %0 : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
    %5 = cir.cast bitcast %0 : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!rec_P>
    %6 = cir.load %5 : !cir.ptr<!rec_P>, !rec_P
    %7 = cir.alloca "p" align(8) init : !cir.ptr<!rec_P>
    %8 = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
    %9 = cir.alloca "q" align(8) init : !cir.ptr<!rec_P>
    cir.store %6, %7 : !rec_P, !cir.ptr<!rec_P>
    cir.copy %7 align(8) to %9 align(8) : !cir.ptr<!rec_P>
    %10 = cir.get_member %9[0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
    %11 = cir.load align(8) %10 : !cir.ptr<!cir.double>, !cir.double
    %12 = cir.get_member %9[1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
    %13 = cir.load align(8) %12 : !cir.ptr<!cir.double>, !cir.double
    %14 = cir.fmul %11, %13 : !cir.double
    cir.store %14, %8 : !cir.double, !cir.ptr<!cir.double>
    %15 = cir.load %8 : !cir.ptr<!cir.double>, !cir.double
    cir.return %15 : !cir.double
  }
  cir.func @dassign(%x: !cir.double, %dx: !cir.double, %y: !cir.double, %dy: !cir.double) -> !cir.double {
    %r = enzyme.fwddiff @assign(%x, %dx, %y, %dy) { activity=[#enzyme.activity<enzyme_dup>, #enzyme.activity<enzyme_dup>], ret_activity=[#enzyme.activity<enzyme_dupnoneed>] } : (!cir.double, !cir.double, !cir.double, !cir.double) -> !cir.double
    cir.return %r : !cir.double
  }
}

// CHECK-LABEL:   cir.func private @fwddiffeassign(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG2:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG3:[a-zA-Z0-9$._-]+]]: !cir.double) -> !cir.double {
// CHECK:           %[[ALLOCA_0:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           %[[ALLOCA_1:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           %[[ALLOCA_2:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           %[[ALLOCA_3:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           %[[GET_MEMBER_0:.*]] = cir.get_member %[[ALLOCA_2]][0] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_1:.*]] = cir.get_member %[[ALLOCA_3]][0] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG1]], %[[GET_MEMBER_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG0]], %[[GET_MEMBER_1]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_2:.*]] = cir.get_member %[[ALLOCA_2]][1] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_3:.*]] = cir.get_member %[[ALLOCA_3]][1] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG3]], %[[GET_MEMBER_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG2]], %[[GET_MEMBER_3]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_0:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
// CHECK:           %[[LOAD_1:.*]] = cir.load %[[ALLOCA_3]] : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
// CHECK:           cir.store %[[LOAD_0]], %[[ALLOCA_0]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           cir.store %[[LOAD_1]], %[[ALLOCA_1]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           %[[CAST_0:.*]] = cir.cast bitcast %[[ALLOCA_0]] : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!rec_P>
// CHECK:           %[[CAST_1:.*]] = cir.cast bitcast %[[ALLOCA_1]] : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!rec_P>
// CHECK:           %[[LOAD_2:.*]] = cir.load %[[CAST_0]] : !cir.ptr<!rec_P>, !rec_P
// CHECK:           %[[LOAD_3:.*]] = cir.load %[[CAST_1]] : !cir.ptr<!rec_P>, !rec_P
// CHECK:           %[[ALLOCA_4:.*]] = cir.alloca "p" align(8) init : !cir.ptr<!rec_P>
// CHECK:           %[[ALLOCA_5:.*]] = cir.alloca "p" align(8) init : !cir.ptr<!rec_P>
// CHECK:           %[[ALLOCA_6:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_7:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_8:.*]] = cir.alloca "q" align(8) init : !cir.ptr<!rec_P>
// CHECK:           %[[ALLOCA_9:.*]] = cir.alloca "q" align(8) init : !cir.ptr<!rec_P>
// CHECK:           cir.store %[[LOAD_2]], %[[ALLOCA_4]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           cir.store %[[LOAD_3]], %[[ALLOCA_5]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           cir.copy %[[ALLOCA_4]] align(8) to %[[ALLOCA_8]] align(8) : !cir.ptr<!rec_P>
// CHECK:           cir.copy %[[ALLOCA_5]] align(8) to %[[ALLOCA_9]] align(8) : !cir.ptr<!rec_P>
// CHECK:           %[[GET_MEMBER_4:.*]] = cir.get_member %[[ALLOCA_8]][0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_5:.*]] = cir.get_member %[[ALLOCA_9]][0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_4:.*]] = cir.load align(8) %[[GET_MEMBER_4]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_5:.*]] = cir.load align(8) %[[GET_MEMBER_5]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[GET_MEMBER_6:.*]] = cir.get_member %[[ALLOCA_8]][1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_7:.*]] = cir.get_member %[[ALLOCA_9]][1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_6:.*]] = cir.load align(8) %[[GET_MEMBER_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_7:.*]] = cir.load align(8) %[[GET_MEMBER_7]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[LOAD_4]], %[[LOAD_7]] : !cir.double
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[LOAD_6]], %[[LOAD_5]] : !cir.double
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[FMUL_0]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[FMUL_2:.*]] = cir.fmul %[[LOAD_5]], %[[LOAD_7]] : !cir.double
// CHECK:           cir.store %[[FADD_0]], %[[ALLOCA_6]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[FMUL_2]], %[[ALLOCA_7]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_8:.*]] = cir.load %[[ALLOCA_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           cir.return %[[LOAD_8]] : !cir.double
// CHECK:         }
