// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize --remove-unnecessary-enzyme-ops --canonicalize %s | FileCheck %s

// Two active arguments give two gradients, but a cir.func returns one value:
// they are packed into an anonymous record and unpacked with
// cir.extract_member, like llvm.func.

!rec = !cir.struct<{data !cir.double, data !cir.double}>
module {
  cir.func @f(%x: !cir.double, %y: !cir.double) -> !cir.double {
    %0 = cir.fmul %x, %y : !cir.double
    cir.return %0 : !cir.double
  }
  cir.func @df(%x: !cir.double, %y: !cir.double, %dr: !cir.double) -> !cir.double {
    %res = enzyme.autodiff @f(%x, %y, %dr) { activity=[#enzyme.activity<enzyme_active>, #enzyme.activity<enzyme_active>], ret_activity=[#enzyme.activity<enzyme_activenoneed>] } : (!cir.double, !cir.double, !cir.double) -> !rec
    %dx = cir.extract_member %res[0] : !rec -> !cir.double
    %dy = cir.extract_member %res[1] : !rec -> !cir.double
    %s = cir.fadd %dx, %dy : !cir.double
    cir.return %s : !cir.double
  }
}

// CHECK-LABEL:   cir.func private @diffef(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG2:[a-zA-Z0-9$._-]+]]: !cir.double) -> !rec_anon_struct {
// CHECK:           %[[CONST_0:.*]] = cir.const #cir.zero : !rec_anon_struct
// CHECK:           %[[CONST_1:.*]] = cir.const #cir.fp<0.000000e+00> : !cir.double
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[CONST_1]], %[[ARG2]] : !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[FADD_0]], %[[ARG1]] : !cir.double
// CHECK:           %[[FADD_1:.*]] = cir.fadd %[[CONST_1]], %[[FMUL_0]] : !cir.double
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[FADD_0]], %[[ARG0]] : !cir.double
// CHECK:           %[[FADD_2:.*]] = cir.fadd %[[CONST_1]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_0:.*]] = cir.insert_member %[[CONST_0]][0], %[[FADD_1]] : !rec_anon_struct, !cir.double
// CHECK:           %[[INSERT_MEMBER_1:.*]] = cir.insert_member %[[INSERT_MEMBER_0]][1], %[[FADD_2]] : !rec_anon_struct, !cir.double
// CHECK:           cir.return %[[INSERT_MEMBER_1]] : !rec_anon_struct
// CHECK:         }
