// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize --remove-unnecessary-enzyme-ops --canonicalize %s | FileCheck %s

// Flattened output of clang -fclangir -emit-cir -O0 -fno-math-errno for
//   double cond(double x) { if (x > 0) return x * x; else return -x; }

!s32i = !cir.int<s, 32>
module {
  cir.func @cond(%arg0: !cir.double ) -> !cir.double {
    %0 = cir.const #cir.int<0> : !s32i
    %1 = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
    %2 = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
    cir.store %arg0, %1 : !cir.double, !cir.ptr<!cir.double>
    %3 = cir.load align(8) %1 : !cir.ptr<!cir.double>, !cir.double
    %4 = cir.cast int_to_float %0 : !s32i -> !cir.double
    %5 = cir.cmp gt %3, %4 : !cir.double
    cir.brcond %5 ^bb1, ^bb2
  ^bb1:  // pred: ^bb0
    %6 = cir.load align(8) %1 : !cir.ptr<!cir.double>, !cir.double
    %7 = cir.load align(8) %1 : !cir.ptr<!cir.double>, !cir.double
    %8 = cir.fmul %6, %7 : !cir.double
    cir.store %8, %2 : !cir.double, !cir.ptr<!cir.double>
    %9 = cir.load %2 : !cir.ptr<!cir.double>, !cir.double
    cir.return %9 : !cir.double
  ^bb2:  // pred: ^bb0
    %10 = cir.load align(8) %1 : !cir.ptr<!cir.double>, !cir.double
    %11 = cir.fneg %10 : !cir.double
    cir.store %11, %2 : !cir.double, !cir.ptr<!cir.double>
    %12 = cir.load %2 : !cir.ptr<!cir.double>, !cir.double
    cir.return %12 : !cir.double
  }
  cir.func @dcond(%x: !cir.double, %dr: !cir.double) -> !cir.double {
    %r = enzyme.autodiff @cond(%x, %dr) { activity=[#enzyme.activity<enzyme_active>], ret_activity=[#enzyme.activity<enzyme_activenoneed>] } : (!cir.double, !cir.double) -> !cir.double
    cir.return %r : !cir.double
  }
}

// CHECK-LABEL:   cir.func private @diffecond(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.double) -> !cir.double {
// CHECK:           %[[CONST_0:.*]] = cir.const #cir.int<0> : !s32i
// CHECK:           %[[CONST_1:.*]] = cir.const #cir.fp<0.000000e+00> : !cir.double
// CHECK:           %[[VAL_0:.*]] = "enzyme.init"() : () -> !enzyme.Cache<!cir.ptr<!cir.double>>
// CHECK:           %[[VAL_1:.*]] = "enzyme.init"() : () -> !enzyme.Cache<!cir.ptr<!cir.double>>
// CHECK:           %[[ALLOCA_0:.*]] = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_1:.*]] = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_2:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_3:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           "enzyme.push"(%[[VAL_0]], %[[ALLOCA_0]]) : (!enzyme.Cache<!cir.ptr<!cir.double>>, !cir.ptr<!cir.double>) -> ()
// CHECK:           cir.store %[[ARG0]], %[[ALLOCA_1]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           "enzyme.push"(%[[VAL_1]], %[[ALLOCA_0]]) : (!enzyme.Cache<!cir.ptr<!cir.double>>, !cir.ptr<!cir.double>) -> ()
// CHECK:           %[[LOAD_0:.*]] = cir.load align(8) %[[ALLOCA_1]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[CAST_0:.*]] = cir.cast int_to_float %[[CONST_0]] : !s32i -> !cir.double
// CHECK:           %[[CMP_0:.*]] = cir.cmp gt %[[LOAD_0]], %[[CAST_0]] : !cir.double
// CHECK:           cir.brcond %[[CMP_0]] ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           %[[LOAD_1:.*]] = cir.load align(8) %[[ALLOCA_1]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_2:.*]] = cir.load align(8) %[[ALLOCA_1]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[LOAD_1]], %[[LOAD_2]] : !cir.double
// CHECK:           cir.store %[[FMUL_0]], %[[ALLOCA_3]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[CONST_1]], %[[ARG1]] : !cir.double
// CHECK:           %[[LOAD_3:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_1:.*]] = cir.fadd %[[LOAD_3]], %[[FADD_0]] : !cir.double
// CHECK:           cir.store %[[FADD_1]], %[[ALLOCA_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_4:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_2:.*]] = cir.fadd %[[CONST_1]], %[[LOAD_4]] : !cir.double
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[FADD_2]], %[[LOAD_2]] : !cir.double
// CHECK:           %[[FADD_3:.*]] = cir.fadd %[[CONST_1]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[FMUL_2:.*]] = cir.fmul %[[FADD_2]], %[[LOAD_1]] : !cir.double
// CHECK:           %[[FADD_4:.*]] = cir.fadd %[[CONST_1]], %[[FMUL_2]] : !cir.double
// CHECK:           %[[LOAD_5:.*]] = cir.load %[[ALLOCA_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_5:.*]] = cir.fadd %[[LOAD_5]], %[[FADD_4]] : !cir.double
// CHECK:           cir.store %[[FADD_5]], %[[ALLOCA_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_6:.*]] = cir.load %[[ALLOCA_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_6:.*]] = cir.fadd %[[LOAD_6]], %[[FADD_3]] : !cir.double
// CHECK:           cir.store %[[FADD_6]], %[[ALLOCA_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cf.br ^bb3
// CHECK:         ^bb2:
// CHECK:           %[[LOAD_7:.*]] = cir.load align(8) %[[ALLOCA_1]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FNEG_0:.*]] = cir.fneg %[[LOAD_7]] : !cir.double
// CHECK:           cir.store %[[FNEG_0]], %[[ALLOCA_3]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[FADD_7:.*]] = cir.fadd %[[CONST_1]], %[[ARG1]] : !cir.double
// CHECK:           %[[LOAD_8:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_8:.*]] = cir.fadd %[[LOAD_8]], %[[FADD_7]] : !cir.double
// CHECK:           cir.store %[[FADD_8]], %[[ALLOCA_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_9:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_9:.*]] = cir.fadd %[[CONST_1]], %[[LOAD_9]] : !cir.double
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[FNEG_1:.*]] = cir.fneg %[[FADD_9]] : !cir.double
// CHECK:           %[[FADD_10:.*]] = cir.fadd %[[CONST_1]], %[[FNEG_1]] : !cir.double
// CHECK:           %[[LOAD_10:.*]] = cir.load %[[ALLOCA_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_11:.*]] = cir.fadd %[[LOAD_10]], %[[FADD_10]] : !cir.double
// CHECK:           cir.store %[[FADD_11]], %[[ALLOCA_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cf.br ^bb3
// CHECK:         ^bb3:
// CHECK:           %[[VAL_2:.*]] = "enzyme.pop"(%[[VAL_1]]) : (!enzyme.Cache<!cir.ptr<!cir.double>>) -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_11:.*]] = cir.load %[[VAL_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_12:.*]] = cir.fadd %[[LOAD_11]], %[[CONST_1]] : !cir.double
// CHECK:           cir.store %[[FADD_12]], %[[VAL_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[VAL_3:.*]] = "enzyme.pop"(%[[VAL_0]]) : (!enzyme.Cache<!cir.ptr<!cir.double>>) -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_12:.*]] = cir.load %[[VAL_3]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_13:.*]] = cir.fadd %[[CONST_1]], %[[LOAD_12]] : !cir.double
// CHECK:           cir.store %[[CONST_1]], %[[VAL_3]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.return %[[FADD_13]] : !cir.double
// CHECK:         }
