// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize --remove-unnecessary-enzyme-ops --canonicalize %s | FileCheck %s

// One active argument: the gradient is a single value, so no packing of
// multiple results into a record is needed.

// Only x diff is returned as y is a constant.
module {
  cir.func @f(%x: !cir.double, %y: !cir.double) -> !cir.double {
    %0 = cir.fmul %x, %y : !cir.double
    cir.return %0 : !cir.double
  }
  cir.func @df(%x: !cir.double, %y: !cir.double, %dr: !cir.double) -> !cir.double {
    %r = enzyme.autodiff @f(%x, %y, %dr) { activity=[#enzyme.activity<enzyme_active>, #enzyme.activity<enzyme_const>], ret_activity=[#enzyme.activity<enzyme_activenoneed>] } : (!cir.double, !cir.double, !cir.double) -> !cir.double
    cir.return %r : !cir.double
  }
}

// CHECK-LABEL:   cir.func private @diffef(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG2:[a-zA-Z0-9$._-]+]]: !cir.double) -> !cir.double {
// CHECK:           %[[CONST_0:.*]] = cir.const #cir.fp<0.000000e+00> : !cir.double
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[CONST_0]], %[[ARG2]] : !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[FADD_0]], %[[ARG1]] : !cir.double
// CHECK:           %[[FADD_1:.*]] = cir.fadd %[[CONST_0]], %[[FMUL_0]] : !cir.double
// CHECK:           cir.return %[[FADD_1]] : !cir.double
// CHECK:         }
