// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize --remove-unnecessary-enzyme-ops --canonicalize %s | FileCheck %s

// Flattened output of clang -fclangir -emit-cir -O0 -fno-math-errno for
//   struct P { double x, y; };
//   double assign(struct P p) { struct P q = p; return q.x * q.y; }

!rec_P = !cir.struct<"P" {data !cir.double, data !cir.double}>
!rec_anon_struct = !cir.struct<{data !cir.double, data !cir.double}>
module {
  cir.func @assign(%arg0: !cir.double, %arg1: !cir.double) -> !cir.double {
    %0 = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
    %1 = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
    %2 = cir.get_member %1[0] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
    cir.store %arg0, %2 : !cir.double, !cir.ptr<!cir.double>
    %3 = cir.get_member %1[1] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
    cir.store %arg1, %3 : !cir.double, !cir.ptr<!cir.double>
    %4 = cir.load %1 : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
    cir.store %4, %0 : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
    %5 = cir.cast bitcast %0 : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!rec_P>
    %6 = cir.load %5 : !cir.ptr<!rec_P>, !rec_P
    %7 = cir.alloca "p" align(8) init : !cir.ptr<!rec_P>
    %8 = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
    %9 = cir.alloca "q" align(8) init : !cir.ptr<!rec_P>
    cir.store %6, %7 : !rec_P, !cir.ptr<!rec_P>
    cir.copy %7 align(8) to %9 align(8) : !cir.ptr<!rec_P>
    %10 = cir.get_member %9[0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
    %11 = cir.load align(8) %10 : !cir.ptr<!cir.double>, !cir.double
    %12 = cir.get_member %9[1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
    %13 = cir.load align(8) %12 : !cir.ptr<!cir.double>, !cir.double
    %14 = cir.fmul %11, %13 : !cir.double
    cir.store %14, %8 : !cir.double, !cir.ptr<!cir.double>
    %15 = cir.load %8 : !cir.ptr<!cir.double>, !cir.double
    cir.return %15 : !cir.double
  }
  cir.func @dassign(%x: !cir.double, %y: !cir.double, %dr: !cir.double) -> !rec_anon_struct {
    %r = enzyme.autodiff @assign(%x, %y, %dr) { activity=[#enzyme.activity<enzyme_active>, #enzyme.activity<enzyme_active>], ret_activity=[#enzyme.activity<enzyme_activenoneed>] } : (!cir.double, !cir.double, !cir.double) -> !rec_anon_struct
    cir.return %r : !rec_anon_struct
  }
}

// CHECK-LABEL:   cir.func private @diffeassign(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG2:[a-zA-Z0-9$._-]+]]: !cir.double) -> !rec_anon_struct {
// CHECK:           %[[CONST_0:.*]] = cir.const #cir.zero : !rec_P
// CHECK:           %[[CONST_1:.*]] = cir.const #cir.zero : !rec_anon_struct
// CHECK:           %[[CONST_2:.*]] = cir.const #cir.fp<0.000000e+00> : !cir.double
// CHECK:           %[[ALLOCA_0:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_0]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           %[[ALLOCA_1:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           %[[ALLOCA_2:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_2]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           %[[ALLOCA_3:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           %[[GET_MEMBER_0:.*]] = cir.get_member %[[ALLOCA_2]][0] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_1:.*]] = cir.get_member %[[ALLOCA_3]][0] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG0]], %[[GET_MEMBER_1]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_2:.*]] = cir.get_member %[[ALLOCA_2]][1] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_3:.*]] = cir.get_member %[[ALLOCA_3]][1] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG1]], %[[GET_MEMBER_3]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_0:.*]] = cir.load %[[ALLOCA_3]] : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
// CHECK:           cir.store %[[LOAD_0]], %[[ALLOCA_1]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           %[[CAST_0:.*]] = cir.cast bitcast %[[ALLOCA_0]] : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!rec_P>
// CHECK:           %[[CAST_1:.*]] = cir.cast bitcast %[[ALLOCA_1]] : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!rec_P>
// CHECK:           %[[LOAD_1:.*]] = cir.load %[[CAST_1]] : !cir.ptr<!rec_P>, !rec_P
// CHECK:           %[[ALLOCA_4:.*]] = cir.alloca "p" align(8) init : !cir.ptr<!rec_P>
// CHECK:           cir.store %[[CONST_0]], %[[ALLOCA_4]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           %[[ALLOCA_5:.*]] = cir.alloca "p" align(8) init : !cir.ptr<!rec_P>
// CHECK:           %[[ALLOCA_6:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[CONST_2]], %[[ALLOCA_6]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_7:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_8:.*]] = cir.alloca "q" align(8) init : !cir.ptr<!rec_P>
// CHECK:           cir.store %[[CONST_0]], %[[ALLOCA_8]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           %[[ALLOCA_9:.*]] = cir.alloca "q" align(8) init : !cir.ptr<!rec_P>
// CHECK:           cir.store %[[LOAD_1]], %[[ALLOCA_5]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           cir.copy %[[ALLOCA_4]] align(8) to %[[ALLOCA_8]] align(8) : !cir.ptr<!rec_P>
// CHECK:           cir.copy %[[ALLOCA_5]] align(8) to %[[ALLOCA_9]] align(8) : !cir.ptr<!rec_P>
// CHECK:           %[[GET_MEMBER_4:.*]] = cir.get_member %[[ALLOCA_8]][0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_5:.*]] = cir.get_member %[[ALLOCA_9]][0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_2:.*]] = cir.load align(8) %[[GET_MEMBER_5]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[GET_MEMBER_6:.*]] = cir.get_member %[[ALLOCA_8]][1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_7:.*]] = cir.get_member %[[ALLOCA_9]][1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_3:.*]] = cir.load align(8) %[[GET_MEMBER_7]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[LOAD_2]], %[[LOAD_3]] : !cir.double
// CHECK:           cir.store %[[FMUL_0]], %[[ALLOCA_7]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[CONST_2]], %[[ARG2]] : !cir.double
// CHECK:           %[[LOAD_4:.*]] = cir.load %[[ALLOCA_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_1:.*]] = cir.fadd %[[LOAD_4]], %[[FADD_0]] : !cir.double
// CHECK:           cir.store %[[FADD_1]], %[[ALLOCA_6]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_5:.*]] = cir.load %[[ALLOCA_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_2:.*]] = cir.fadd %[[CONST_2]], %[[LOAD_5]] : !cir.double
// CHECK:           cir.store %[[CONST_2]], %[[ALLOCA_6]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[FADD_2]], %[[LOAD_3]] : !cir.double
// CHECK:           %[[FADD_3:.*]] = cir.fadd %[[CONST_2]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[FMUL_2:.*]] = cir.fmul %[[FADD_2]], %[[LOAD_2]] : !cir.double
// CHECK:           %[[FADD_4:.*]] = cir.fadd %[[CONST_2]], %[[FMUL_2]] : !cir.double
// CHECK:           %[[LOAD_6:.*]] = cir.load %[[GET_MEMBER_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_5:.*]] = cir.fadd %[[LOAD_6]], %[[FADD_4]] : !cir.double
// CHECK:           cir.store %[[FADD_5]], %[[GET_MEMBER_6]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_7:.*]] = cir.load %[[GET_MEMBER_4]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_6:.*]] = cir.fadd %[[LOAD_7]], %[[FADD_3]] : !cir.double
// CHECK:           cir.store %[[FADD_6]], %[[GET_MEMBER_4]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_8:.*]] = cir.load %[[ALLOCA_8]] : !cir.ptr<!rec_P>, !rec_P
// CHECK:           %[[LOAD_9:.*]] = cir.load %[[ALLOCA_4]] : !cir.ptr<!rec_P>, !rec_P
// CHECK:           %[[EXTRACT_MEMBER_0:.*]] = cir.extract_member %[[LOAD_9]][0] : !rec_P -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_1:.*]] = cir.extract_member %[[LOAD_8]][0] : !rec_P -> !cir.double
// CHECK:           %[[FADD_7:.*]] = cir.fadd %[[EXTRACT_MEMBER_0]], %[[EXTRACT_MEMBER_1]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_0:.*]] = cir.insert_member %[[CONST_0]][0], %[[FADD_7]] : !rec_P, !cir.double
// CHECK:           %[[EXTRACT_MEMBER_2:.*]] = cir.extract_member %[[LOAD_9]][1] : !rec_P -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_3:.*]] = cir.extract_member %[[LOAD_8]][1] : !rec_P -> !cir.double
// CHECK:           %[[FADD_8:.*]] = cir.fadd %[[EXTRACT_MEMBER_2]], %[[EXTRACT_MEMBER_3]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_1:.*]] = cir.insert_member %[[INSERT_MEMBER_0]][1], %[[FADD_8]] : !rec_P, !cir.double
// CHECK:           cir.store %[[INSERT_MEMBER_1]], %[[ALLOCA_4]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           cir.store %[[CONST_0]], %[[ALLOCA_8]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           %[[LOAD_10:.*]] = cir.load %[[ALLOCA_4]] : !cir.ptr<!rec_P>, !rec_P
// CHECK:           %[[EXTRACT_MEMBER_4:.*]] = cir.extract_member %[[CONST_0]][0] : !rec_P -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_5:.*]] = cir.extract_member %[[LOAD_10]][0] : !rec_P -> !cir.double
// CHECK:           %[[FADD_9:.*]] = cir.fadd %[[EXTRACT_MEMBER_4]], %[[EXTRACT_MEMBER_5]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_2:.*]] = cir.insert_member %[[CONST_0]][0], %[[FADD_9]] : !rec_P, !cir.double
// CHECK:           %[[EXTRACT_MEMBER_6:.*]] = cir.extract_member %[[CONST_0]][1] : !rec_P -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_7:.*]] = cir.extract_member %[[LOAD_10]][1] : !rec_P -> !cir.double
// CHECK:           %[[FADD_10:.*]] = cir.fadd %[[EXTRACT_MEMBER_6]], %[[EXTRACT_MEMBER_7]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_3:.*]] = cir.insert_member %[[INSERT_MEMBER_2]][1], %[[FADD_10]] : !rec_P, !cir.double
// CHECK:           cir.store %[[CONST_0]], %[[ALLOCA_4]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           %[[LOAD_11:.*]] = cir.load %[[CAST_0]] : !cir.ptr<!rec_P>, !rec_P
// CHECK:           %[[EXTRACT_MEMBER_8:.*]] = cir.extract_member %[[LOAD_11]][0] : !rec_P -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_9:.*]] = cir.extract_member %[[INSERT_MEMBER_3]][0] : !rec_P -> !cir.double
// CHECK:           %[[FADD_11:.*]] = cir.fadd %[[EXTRACT_MEMBER_8]], %[[EXTRACT_MEMBER_9]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_4:.*]] = cir.insert_member %[[CONST_0]][0], %[[FADD_11]] : !rec_P, !cir.double
// CHECK:           %[[EXTRACT_MEMBER_10:.*]] = cir.extract_member %[[LOAD_11]][1] : !rec_P -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_11:.*]] = cir.extract_member %[[INSERT_MEMBER_3]][1] : !rec_P -> !cir.double
// CHECK:           %[[FADD_12:.*]] = cir.fadd %[[EXTRACT_MEMBER_10]], %[[EXTRACT_MEMBER_11]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_5:.*]] = cir.insert_member %[[INSERT_MEMBER_4]][1], %[[FADD_12]] : !rec_P, !cir.double
// CHECK:           cir.store %[[INSERT_MEMBER_5]], %[[CAST_0]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           %[[LOAD_12:.*]] = cir.load %[[ALLOCA_0]] : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
// CHECK:           %[[EXTRACT_MEMBER_12:.*]] = cir.extract_member %[[CONST_1]][0] : !rec_anon_struct -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_13:.*]] = cir.extract_member %[[LOAD_12]][0] : !rec_anon_struct -> !cir.double
// CHECK:           %[[FADD_13:.*]] = cir.fadd %[[EXTRACT_MEMBER_12]], %[[EXTRACT_MEMBER_13]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_6:.*]] = cir.insert_member %[[CONST_1]][0], %[[FADD_13]] : !rec_anon_struct, !cir.double
// CHECK:           %[[EXTRACT_MEMBER_14:.*]] = cir.extract_member %[[CONST_1]][1] : !rec_anon_struct -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_15:.*]] = cir.extract_member %[[LOAD_12]][1] : !rec_anon_struct -> !cir.double
// CHECK:           %[[FADD_14:.*]] = cir.fadd %[[EXTRACT_MEMBER_14]], %[[EXTRACT_MEMBER_15]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_7:.*]] = cir.insert_member %[[INSERT_MEMBER_6]][1], %[[FADD_14]] : !rec_anon_struct, !cir.double
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_0]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           %[[LOAD_13:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
// CHECK:           %[[EXTRACT_MEMBER_16:.*]] = cir.extract_member %[[LOAD_13]][0] : !rec_anon_struct -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_17:.*]] = cir.extract_member %[[INSERT_MEMBER_7]][0] : !rec_anon_struct -> !cir.double
// CHECK:           %[[FADD_15:.*]] = cir.fadd %[[EXTRACT_MEMBER_16]], %[[EXTRACT_MEMBER_17]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_8:.*]] = cir.insert_member %[[CONST_1]][0], %[[FADD_15]] : !rec_anon_struct, !cir.double
// CHECK:           %[[EXTRACT_MEMBER_18:.*]] = cir.extract_member %[[LOAD_13]][1] : !rec_anon_struct -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_19:.*]] = cir.extract_member %[[INSERT_MEMBER_7]][1] : !rec_anon_struct -> !cir.double
// CHECK:           %[[FADD_16:.*]] = cir.fadd %[[EXTRACT_MEMBER_18]], %[[EXTRACT_MEMBER_19]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_9:.*]] = cir.insert_member %[[INSERT_MEMBER_8]][1], %[[FADD_16]] : !rec_anon_struct, !cir.double
// CHECK:           cir.store %[[INSERT_MEMBER_9]], %[[ALLOCA_2]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           %[[LOAD_14:.*]] = cir.load %[[GET_MEMBER_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_17:.*]] = cir.fadd %[[CONST_2]], %[[LOAD_14]] : !cir.double
// CHECK:           cir.store %[[CONST_2]], %[[GET_MEMBER_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_15:.*]] = cir.load %[[GET_MEMBER_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_18:.*]] = cir.fadd %[[CONST_2]], %[[LOAD_15]] : !cir.double
// CHECK:           cir.store %[[CONST_2]], %[[GET_MEMBER_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[INSERT_MEMBER_10:.*]] = cir.insert_member %[[CONST_1]][0], %[[FADD_18]] : !rec_anon_struct, !cir.double
// CHECK:           %[[INSERT_MEMBER_11:.*]] = cir.insert_member %[[INSERT_MEMBER_10]][1], %[[FADD_17]] : !rec_anon_struct, !cir.double
// CHECK:           cir.return %[[INSERT_MEMBER_11]] : !rec_anon_struct
// CHECK:         }
