// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize --remove-unnecessary-enzyme-ops --canonicalize %s | FileCheck %s

// Flattened output of clang -fclangir -emit-cir -O0 -fno-math-errno for
//   struct P { double x, y; };
//   double norm2(struct P p) { return p.x * p.x + p.y * p.y; }

!rec_P = !cir.struct<"P" {data !cir.double, data !cir.double}>
!rec_anon_struct = !cir.struct<{data !cir.double, data !cir.double}>
module {
  cir.func @norm2(%arg0: !cir.double, %arg1: !cir.double) -> !cir.double {
    %0 = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
    %1 = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
    %2 = cir.get_member %1[0] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
    cir.store %arg0, %2 : !cir.double, !cir.ptr<!cir.double>
    %3 = cir.get_member %1[1] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
    cir.store %arg1, %3 : !cir.double, !cir.ptr<!cir.double>
    %4 = cir.load %1 : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
    cir.store %4, %0 : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
    %5 = cir.cast bitcast %0 : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!rec_P>
    %6 = cir.load %5 : !cir.ptr<!rec_P>, !rec_P
    %7 = cir.alloca "p" align(8) init : !cir.ptr<!rec_P>
    %8 = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
    cir.store %6, %7 : !rec_P, !cir.ptr<!rec_P>
    %9 = cir.get_member %7[0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
    %10 = cir.load align(8) %9 : !cir.ptr<!cir.double>, !cir.double
    %11 = cir.get_member %7[0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
    %12 = cir.load align(8) %11 : !cir.ptr<!cir.double>, !cir.double
    %13 = cir.get_member %7[1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
    %14 = cir.load align(8) %13 : !cir.ptr<!cir.double>, !cir.double
    %15 = cir.get_member %7[1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
    %16 = cir.load align(8) %15 : !cir.ptr<!cir.double>, !cir.double
    %17 = cir.fmul %14, %16 : !cir.double
    %18 = cir.fmuladd %10, %12, %17 : !cir.double
    cir.store %18, %8 : !cir.double, !cir.ptr<!cir.double>
    %19 = cir.load %8 : !cir.ptr<!cir.double>, !cir.double
    cir.return %19 : !cir.double
  }
  cir.func @dnorm2(%x: !cir.double, %y: !cir.double, %dr: !cir.double) -> !rec_anon_struct {
    %r = enzyme.autodiff @norm2(%x, %y, %dr) { activity=[#enzyme.activity<enzyme_active>, #enzyme.activity<enzyme_active>], ret_activity=[#enzyme.activity<enzyme_activenoneed>] } : (!cir.double, !cir.double, !cir.double) -> !rec_anon_struct
    cir.return %r : !rec_anon_struct
  }
}

// CHECK-LABEL:   cir.func private @diffenorm2(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG2:[a-zA-Z0-9$._-]+]]: !cir.double) -> !rec_anon_struct {
// CHECK:           %[[CONST_0:.*]] = cir.const #cir.zero : !rec_P
// CHECK:           %[[CONST_1:.*]] = cir.const #cir.zero : !rec_anon_struct
// CHECK:           %[[CONST_2:.*]] = cir.const #cir.fp<0.000000e+00> : !cir.double
// CHECK:           %[[ALLOCA_0:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_0]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           %[[ALLOCA_1:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           %[[ALLOCA_2:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_2]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           %[[ALLOCA_3:.*]] = cir.alloca "coerce" align(8) : !cir.ptr<!rec_anon_struct>
// CHECK:           %[[GET_MEMBER_0:.*]] = cir.get_member %[[ALLOCA_2]][0] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_1:.*]] = cir.get_member %[[ALLOCA_3]][0] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG0]], %[[GET_MEMBER_1]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_2:.*]] = cir.get_member %[[ALLOCA_2]][1] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_3:.*]] = cir.get_member %[[ALLOCA_3]][1] {name = ""} : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG1]], %[[GET_MEMBER_3]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_0:.*]] = cir.load %[[ALLOCA_3]] : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
// CHECK:           cir.store %[[LOAD_0]], %[[ALLOCA_1]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           %[[CAST_0:.*]] = cir.cast bitcast %[[ALLOCA_0]] : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!rec_P>
// CHECK:           %[[CAST_1:.*]] = cir.cast bitcast %[[ALLOCA_1]] : !cir.ptr<!rec_anon_struct> -> !cir.ptr<!rec_P>
// CHECK:           %[[LOAD_1:.*]] = cir.load %[[CAST_1]] : !cir.ptr<!rec_P>, !rec_P
// CHECK:           %[[ALLOCA_4:.*]] = cir.alloca "p" align(8) init : !cir.ptr<!rec_P>
// CHECK:           cir.store %[[CONST_0]], %[[ALLOCA_4]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           %[[ALLOCA_5:.*]] = cir.alloca "p" align(8) init : !cir.ptr<!rec_P>
// CHECK:           %[[ALLOCA_6:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[CONST_2]], %[[ALLOCA_6]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_7:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[LOAD_1]], %[[ALLOCA_5]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           %[[GET_MEMBER_4:.*]] = cir.get_member %[[ALLOCA_4]][0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_5:.*]] = cir.get_member %[[ALLOCA_5]][0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_2:.*]] = cir.load align(8) %[[GET_MEMBER_5]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[GET_MEMBER_6:.*]] = cir.get_member %[[ALLOCA_4]][0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_7:.*]] = cir.get_member %[[ALLOCA_5]][0] {name = "x"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_3:.*]] = cir.load align(8) %[[GET_MEMBER_7]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[GET_MEMBER_8:.*]] = cir.get_member %[[ALLOCA_4]][1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_9:.*]] = cir.get_member %[[ALLOCA_5]][1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_4:.*]] = cir.load align(8) %[[GET_MEMBER_9]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[GET_MEMBER_10:.*]] = cir.get_member %[[ALLOCA_4]][1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[GET_MEMBER_11:.*]] = cir.get_member %[[ALLOCA_5]][1] {name = "y"} : !cir.ptr<!rec_P> -> !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_5:.*]] = cir.load align(8) %[[GET_MEMBER_11]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[LOAD_4]], %[[LOAD_5]] : !cir.double
// CHECK:           %[[FMULADD_0:.*]] = cir.fmuladd %[[LOAD_2]], %[[LOAD_3]], %[[FMUL_0]] : !cir.double
// CHECK:           cir.store %[[FMULADD_0]], %[[ALLOCA_7]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[CONST_2]], %[[ARG2]] : !cir.double
// CHECK:           %[[LOAD_6:.*]] = cir.load %[[ALLOCA_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_1:.*]] = cir.fadd %[[LOAD_6]], %[[FADD_0]] : !cir.double
// CHECK:           cir.store %[[FADD_1]], %[[ALLOCA_6]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_7:.*]] = cir.load %[[ALLOCA_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_2:.*]] = cir.fadd %[[CONST_2]], %[[LOAD_7]] : !cir.double
// CHECK:           cir.store %[[CONST_2]], %[[ALLOCA_6]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[FADD_2]], %[[LOAD_3]] : !cir.double
// CHECK:           %[[FADD_3:.*]] = cir.fadd %[[CONST_2]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[FMUL_2:.*]] = cir.fmul %[[FADD_2]], %[[LOAD_2]] : !cir.double
// CHECK:           %[[FADD_4:.*]] = cir.fadd %[[CONST_2]], %[[FMUL_2]] : !cir.double
// CHECK:           %[[FADD_5:.*]] = cir.fadd %[[CONST_2]], %[[FADD_2]] : !cir.double
// CHECK:           %[[FMUL_3:.*]] = cir.fmul %[[FADD_5]], %[[LOAD_5]] : !cir.double
// CHECK:           %[[FADD_6:.*]] = cir.fadd %[[CONST_2]], %[[FMUL_3]] : !cir.double
// CHECK:           %[[FMUL_4:.*]] = cir.fmul %[[FADD_5]], %[[LOAD_4]] : !cir.double
// CHECK:           %[[FADD_7:.*]] = cir.fadd %[[CONST_2]], %[[FMUL_4]] : !cir.double
// CHECK:           %[[LOAD_8:.*]] = cir.load %[[GET_MEMBER_10]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_8:.*]] = cir.fadd %[[LOAD_8]], %[[FADD_7]] : !cir.double
// CHECK:           cir.store %[[FADD_8]], %[[GET_MEMBER_10]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_9:.*]] = cir.load %[[GET_MEMBER_8]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_9:.*]] = cir.fadd %[[LOAD_9]], %[[FADD_6]] : !cir.double
// CHECK:           cir.store %[[FADD_9]], %[[GET_MEMBER_8]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_10:.*]] = cir.load %[[GET_MEMBER_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_10:.*]] = cir.fadd %[[LOAD_10]], %[[FADD_4]] : !cir.double
// CHECK:           cir.store %[[FADD_10]], %[[GET_MEMBER_6]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_11:.*]] = cir.load %[[GET_MEMBER_4]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_11:.*]] = cir.fadd %[[LOAD_11]], %[[FADD_3]] : !cir.double
// CHECK:           cir.store %[[FADD_11]], %[[GET_MEMBER_4]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_12:.*]] = cir.load %[[ALLOCA_4]] : !cir.ptr<!rec_P>, !rec_P
// CHECK:           %[[EXTRACT_MEMBER_0:.*]] = cir.extract_member %[[CONST_0]][0] : !rec_P -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_1:.*]] = cir.extract_member %[[LOAD_12]][0] : !rec_P -> !cir.double
// CHECK:           %[[FADD_12:.*]] = cir.fadd %[[EXTRACT_MEMBER_0]], %[[EXTRACT_MEMBER_1]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_0:.*]] = cir.insert_member %[[CONST_0]][0], %[[FADD_12]] : !rec_P, !cir.double
// CHECK:           %[[EXTRACT_MEMBER_2:.*]] = cir.extract_member %[[CONST_0]][1] : !rec_P -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_3:.*]] = cir.extract_member %[[LOAD_12]][1] : !rec_P -> !cir.double
// CHECK:           %[[FADD_13:.*]] = cir.fadd %[[EXTRACT_MEMBER_2]], %[[EXTRACT_MEMBER_3]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_1:.*]] = cir.insert_member %[[INSERT_MEMBER_0]][1], %[[FADD_13]] : !rec_P, !cir.double
// CHECK:           cir.store %[[CONST_0]], %[[ALLOCA_4]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           %[[LOAD_13:.*]] = cir.load %[[CAST_0]] : !cir.ptr<!rec_P>, !rec_P
// CHECK:           %[[EXTRACT_MEMBER_4:.*]] = cir.extract_member %[[LOAD_13]][0] : !rec_P -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_5:.*]] = cir.extract_member %[[INSERT_MEMBER_1]][0] : !rec_P -> !cir.double
// CHECK:           %[[FADD_14:.*]] = cir.fadd %[[EXTRACT_MEMBER_4]], %[[EXTRACT_MEMBER_5]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_2:.*]] = cir.insert_member %[[CONST_0]][0], %[[FADD_14]] : !rec_P, !cir.double
// CHECK:           %[[EXTRACT_MEMBER_6:.*]] = cir.extract_member %[[LOAD_13]][1] : !rec_P -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_7:.*]] = cir.extract_member %[[INSERT_MEMBER_1]][1] : !rec_P -> !cir.double
// CHECK:           %[[FADD_15:.*]] = cir.fadd %[[EXTRACT_MEMBER_6]], %[[EXTRACT_MEMBER_7]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_3:.*]] = cir.insert_member %[[INSERT_MEMBER_2]][1], %[[FADD_15]] : !rec_P, !cir.double
// CHECK:           cir.store %[[INSERT_MEMBER_3]], %[[CAST_0]] : !rec_P, !cir.ptr<!rec_P>
// CHECK:           %[[LOAD_14:.*]] = cir.load %[[ALLOCA_0]] : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
// CHECK:           %[[EXTRACT_MEMBER_8:.*]] = cir.extract_member %[[CONST_1]][0] : !rec_anon_struct -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_9:.*]] = cir.extract_member %[[LOAD_14]][0] : !rec_anon_struct -> !cir.double
// CHECK:           %[[FADD_16:.*]] = cir.fadd %[[EXTRACT_MEMBER_8]], %[[EXTRACT_MEMBER_9]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_4:.*]] = cir.insert_member %[[CONST_1]][0], %[[FADD_16]] : !rec_anon_struct, !cir.double
// CHECK:           %[[EXTRACT_MEMBER_10:.*]] = cir.extract_member %[[CONST_1]][1] : !rec_anon_struct -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_11:.*]] = cir.extract_member %[[LOAD_14]][1] : !rec_anon_struct -> !cir.double
// CHECK:           %[[FADD_17:.*]] = cir.fadd %[[EXTRACT_MEMBER_10]], %[[EXTRACT_MEMBER_11]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_5:.*]] = cir.insert_member %[[INSERT_MEMBER_4]][1], %[[FADD_17]] : !rec_anon_struct, !cir.double
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_0]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           %[[LOAD_15:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!rec_anon_struct>, !rec_anon_struct
// CHECK:           %[[EXTRACT_MEMBER_12:.*]] = cir.extract_member %[[LOAD_15]][0] : !rec_anon_struct -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_13:.*]] = cir.extract_member %[[INSERT_MEMBER_5]][0] : !rec_anon_struct -> !cir.double
// CHECK:           %[[FADD_18:.*]] = cir.fadd %[[EXTRACT_MEMBER_12]], %[[EXTRACT_MEMBER_13]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_6:.*]] = cir.insert_member %[[CONST_1]][0], %[[FADD_18]] : !rec_anon_struct, !cir.double
// CHECK:           %[[EXTRACT_MEMBER_14:.*]] = cir.extract_member %[[LOAD_15]][1] : !rec_anon_struct -> !cir.double
// CHECK:           %[[EXTRACT_MEMBER_15:.*]] = cir.extract_member %[[INSERT_MEMBER_5]][1] : !rec_anon_struct -> !cir.double
// CHECK:           %[[FADD_19:.*]] = cir.fadd %[[EXTRACT_MEMBER_14]], %[[EXTRACT_MEMBER_15]] : !cir.double
// CHECK:           %[[INSERT_MEMBER_7:.*]] = cir.insert_member %[[INSERT_MEMBER_6]][1], %[[FADD_19]] : !rec_anon_struct, !cir.double
// CHECK:           cir.store %[[INSERT_MEMBER_7]], %[[ALLOCA_2]] : !rec_anon_struct, !cir.ptr<!rec_anon_struct>
// CHECK:           %[[LOAD_16:.*]] = cir.load %[[GET_MEMBER_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_20:.*]] = cir.fadd %[[CONST_2]], %[[LOAD_16]] : !cir.double
// CHECK:           cir.store %[[CONST_2]], %[[GET_MEMBER_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_17:.*]] = cir.load %[[GET_MEMBER_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_21:.*]] = cir.fadd %[[CONST_2]], %[[LOAD_17]] : !cir.double
// CHECK:           cir.store %[[CONST_2]], %[[GET_MEMBER_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[INSERT_MEMBER_8:.*]] = cir.insert_member %[[CONST_1]][0], %[[FADD_21]] : !rec_anon_struct, !cir.double
// CHECK:           %[[INSERT_MEMBER_9:.*]] = cir.insert_member %[[INSERT_MEMBER_8]][1], %[[FADD_20]] : !rec_anon_struct, !cir.double
// CHECK:           cir.return %[[INSERT_MEMBER_9]] : !rec_anon_struct
// CHECK:         }
