// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize --remove-unnecessary-enzyme-ops --canonicalize %s | FileCheck %s

// Flattened output of clang -fclangir -emit-cir -O0 -fno-math-errno for
//   double square(double x) { return x * x; }

module {
  cir.func @square(%arg0: !cir.double ) -> !cir.double {
    %0 = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
    %1 = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
    cir.store %arg0, %0 : !cir.double, !cir.ptr<!cir.double>
    %2 = cir.load align(8) %0 : !cir.ptr<!cir.double>, !cir.double
    %3 = cir.load align(8) %0 : !cir.ptr<!cir.double>, !cir.double
    %4 = cir.fmul %2, %3 : !cir.double
    cir.store %4, %1 : !cir.double, !cir.ptr<!cir.double>
    %5 = cir.load %1 : !cir.ptr<!cir.double>, !cir.double
    cir.return %5 : !cir.double
  }
  cir.func @dsquare(%x: !cir.double, %dr: !cir.double) -> !cir.double {
    %r = enzyme.autodiff @square(%x, %dr) { activity=[#enzyme.activity<enzyme_active>], ret_activity=[#enzyme.activity<enzyme_activenoneed>] } : (!cir.double, !cir.double) -> !cir.double
    cir.return %r : !cir.double
  }
}

// CHECK-LABEL:   cir.func private @diffesquare(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.double) -> !cir.double {
// CHECK:           %[[CONST_0:.*]] = cir.const #cir.fp<0.000000e+00> : !cir.double
// CHECK:           %[[ALLOCA_0:.*]] = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[CONST_0]], %[[ALLOCA_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_1:.*]] = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_2:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[CONST_0]], %[[ALLOCA_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_3:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG0]], %[[ALLOCA_1]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_0:.*]] = cir.load align(8) %[[ALLOCA_1]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_1:.*]] = cir.load align(8) %[[ALLOCA_1]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[LOAD_0]], %[[LOAD_1]] : !cir.double
// CHECK:           cir.store %[[FMUL_0]], %[[ALLOCA_3]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[CONST_0]], %[[ARG1]] : !cir.double
// CHECK:           %[[LOAD_2:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_1:.*]] = cir.fadd %[[LOAD_2]], %[[FADD_0]] : !cir.double
// CHECK:           cir.store %[[FADD_1]], %[[ALLOCA_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_3:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_2:.*]] = cir.fadd %[[CONST_0]], %[[LOAD_3]] : !cir.double
// CHECK:           cir.store %[[CONST_0]], %[[ALLOCA_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[FADD_2]], %[[LOAD_1]] : !cir.double
// CHECK:           %[[FADD_3:.*]] = cir.fadd %[[CONST_0]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[FMUL_2:.*]] = cir.fmul %[[FADD_2]], %[[LOAD_0]] : !cir.double
// CHECK:           %[[FADD_4:.*]] = cir.fadd %[[CONST_0]], %[[FMUL_2]] : !cir.double
// CHECK:           %[[LOAD_4:.*]] = cir.load %[[ALLOCA_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_5:.*]] = cir.fadd %[[LOAD_4]], %[[FADD_4]] : !cir.double
// CHECK:           cir.store %[[FADD_5]], %[[ALLOCA_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_5:.*]] = cir.load %[[ALLOCA_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_6:.*]] = cir.fadd %[[LOAD_5]], %[[FADD_3]] : !cir.double
// CHECK:           cir.store %[[FADD_6]], %[[ALLOCA_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_6:.*]] = cir.load %[[ALLOCA_0]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_7:.*]] = cir.fadd %[[CONST_0]], %[[LOAD_6]] : !cir.double
// CHECK:           cir.store %[[CONST_0]], %[[ALLOCA_0]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.return %[[FADD_7]] : !cir.double
// CHECK:         }
