// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize --remove-unnecessary-enzyme-ops --canonicalize %s | FileCheck %s

// Flattened output of clang -fclangir -emit-cir -O0 -fno-math-errno for
//   float castf(float x) { double d = x; return (float)(d * d); }

module {
  cir.func @castf(%arg0: !cir.float ) -> !cir.float {
    %0 = cir.alloca "x" align(4) init : !cir.ptr<!cir.float>
    %1 = cir.alloca "__retval" align(4) : !cir.ptr<!cir.float>
    %2 = cir.alloca "d" align(8) init : !cir.ptr<!cir.double>
    cir.store %arg0, %0 : !cir.float, !cir.ptr<!cir.float>
    %3 = cir.load align(4) %0 : !cir.ptr<!cir.float>, !cir.float
    %4 = cir.cast floating %3 : !cir.float -> !cir.double
    cir.store align(8) %4, %2 : !cir.double, !cir.ptr<!cir.double>
    %5 = cir.load align(8) %2 : !cir.ptr<!cir.double>, !cir.double
    %6 = cir.load align(8) %2 : !cir.ptr<!cir.double>, !cir.double
    %7 = cir.fmul %5, %6 : !cir.double
    %8 = cir.cast floating %7 : !cir.double -> !cir.float
    cir.store %8, %1 : !cir.float, !cir.ptr<!cir.float>
    %9 = cir.load %1 : !cir.ptr<!cir.float>, !cir.float
    cir.return %9 : !cir.float
  }
  cir.func @dcastf(%x: !cir.float, %dr: !cir.float) -> !cir.float {
    %r = enzyme.autodiff @castf(%x, %dr) { activity=[#enzyme.activity<enzyme_active>], ret_activity=[#enzyme.activity<enzyme_activenoneed>] } : (!cir.float, !cir.float) -> !cir.float
    cir.return %r : !cir.float
  }
}

// CHECK-LABEL:   cir.func private @diffecastf(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.float,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.float) -> !cir.float {
// CHECK:           %[[CONST_0:.*]] = cir.const #cir.fp<0.000000e+00> : !cir.double
// CHECK:           %[[CONST_1:.*]] = cir.const #cir.fp<0.000000e+00> : !cir.float
// CHECK:           %[[ALLOCA_0:.*]] = cir.alloca "x" align(4) init : !cir.ptr<!cir.float>
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_0]] : !cir.float, !cir.ptr<!cir.float>
// CHECK:           %[[ALLOCA_1:.*]] = cir.alloca "x" align(4) init : !cir.ptr<!cir.float>
// CHECK:           %[[ALLOCA_2:.*]] = cir.alloca "__retval" align(4) : !cir.ptr<!cir.float>
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_2]] : !cir.float, !cir.ptr<!cir.float>
// CHECK:           %[[ALLOCA_3:.*]] = cir.alloca "__retval" align(4) : !cir.ptr<!cir.float>
// CHECK:           %[[ALLOCA_4:.*]] = cir.alloca "d" align(8) init : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[CONST_0]], %[[ALLOCA_4]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_5:.*]] = cir.alloca "d" align(8) init : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG0]], %[[ALLOCA_1]] : !cir.float, !cir.ptr<!cir.float>
// CHECK:           %[[LOAD_0:.*]] = cir.load align(4) %[[ALLOCA_1]] : !cir.ptr<!cir.float>, !cir.float
// CHECK:           %[[CAST_0:.*]] = cir.cast floating %[[LOAD_0]] : !cir.float -> !cir.double
// CHECK:           cir.store align(8) %[[CAST_0]], %[[ALLOCA_5]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_1:.*]] = cir.load align(8) %[[ALLOCA_5]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_2:.*]] = cir.load align(8) %[[ALLOCA_5]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[LOAD_1]], %[[LOAD_2]] : !cir.double
// CHECK:           %[[CAST_1:.*]] = cir.cast floating %[[FMUL_0]] : !cir.double -> !cir.float
// CHECK:           cir.store %[[CAST_1]], %[[ALLOCA_3]] : !cir.float, !cir.ptr<!cir.float>
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[CONST_1]], %[[ARG1]] : !cir.float
// CHECK:           %[[LOAD_3:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!cir.float>, !cir.float
// CHECK:           %[[FADD_1:.*]] = cir.fadd %[[LOAD_3]], %[[FADD_0]] : !cir.float
// CHECK:           cir.store %[[FADD_1]], %[[ALLOCA_2]] : !cir.float, !cir.ptr<!cir.float>
// CHECK:           %[[LOAD_4:.*]] = cir.load %[[ALLOCA_2]] : !cir.ptr<!cir.float>, !cir.float
// CHECK:           %[[FADD_2:.*]] = cir.fadd %[[CONST_1]], %[[LOAD_4]] : !cir.float
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_2]] : !cir.float, !cir.ptr<!cir.float>
// CHECK:           %[[CAST_2:.*]] = cir.cast floating %[[FADD_2]] : !cir.float -> !cir.double
// CHECK:           %[[FADD_3:.*]] = cir.fadd %[[CONST_0]], %[[CAST_2]] : !cir.double
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[FADD_3]], %[[LOAD_2]] : !cir.double
// CHECK:           %[[FADD_4:.*]] = cir.fadd %[[CONST_0]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[FMUL_2:.*]] = cir.fmul %[[FADD_3]], %[[LOAD_1]] : !cir.double
// CHECK:           %[[FADD_5:.*]] = cir.fadd %[[CONST_0]], %[[FMUL_2]] : !cir.double
// CHECK:           %[[LOAD_5:.*]] = cir.load %[[ALLOCA_4]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_6:.*]] = cir.fadd %[[LOAD_5]], %[[FADD_5]] : !cir.double
// CHECK:           cir.store %[[FADD_6]], %[[ALLOCA_4]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_6:.*]] = cir.load %[[ALLOCA_4]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_7:.*]] = cir.fadd %[[LOAD_6]], %[[FADD_4]] : !cir.double
// CHECK:           cir.store %[[FADD_7]], %[[ALLOCA_4]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_7:.*]] = cir.load %[[ALLOCA_4]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FADD_8:.*]] = cir.fadd %[[CONST_0]], %[[LOAD_7]] : !cir.double
// CHECK:           cir.store %[[CONST_0]], %[[ALLOCA_4]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[CAST_3:.*]] = cir.cast floating %[[FADD_8]] : !cir.double -> !cir.float
// CHECK:           %[[FADD_9:.*]] = cir.fadd %[[CONST_1]], %[[CAST_3]] : !cir.float
// CHECK:           %[[LOAD_8:.*]] = cir.load %[[ALLOCA_0]] : !cir.ptr<!cir.float>, !cir.float
// CHECK:           %[[FADD_10:.*]] = cir.fadd %[[LOAD_8]], %[[FADD_9]] : !cir.float
// CHECK:           cir.store %[[FADD_10]], %[[ALLOCA_0]] : !cir.float, !cir.ptr<!cir.float>
// CHECK:           %[[LOAD_9:.*]] = cir.load %[[ALLOCA_0]] : !cir.ptr<!cir.float>, !cir.float
// CHECK:           %[[FADD_11:.*]] = cir.fadd %[[CONST_1]], %[[LOAD_9]] : !cir.float
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_0]] : !cir.float, !cir.ptr<!cir.float>
// CHECK:           cir.return %[[FADD_11]] : !cir.float
// CHECK:         }
