;; CUDA sm_120 platform, generated from a Poseidon GPU cost model CSV.
;; Source native_arch tag: sm_120
;; Cost unit: reciprocal throughput as the CSV measured it.
;;
;; Generated by poseidon/tools/herbie/csv_to_herbie_platform.py; pass it
;; to Herbie by path (--platform <this file>). DO NOT HAND-EDIT:
;; regenerate from the CSV instead (poseidon-calibrate --only
;; herbie-platform --out <csv>).

(module cuda-sm120 '|#%embedded:syntax/platform-language:|

(require '|#%embedded:math/flonum:|)

(define 32bit-move-cost   126.562475)
(define 64bit-move-cost   6321.05675)
(define boolean-move-cost 126.562475)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;; BOOLEAN ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define-representation <bool> #:cost boolean-move-cost)

(define-operations () <bool>
  [TRUE  #:spec (TRUE)  #:impl (const true)  #:fpcore TRUE  #:cost boolean-move-cost]
  [FALSE #:spec (FALSE) #:impl (const false) #:fpcore FALSE #:cost boolean-move-cost])

(define-operations ([x <bool>] [y <bool>]) <bool>
  [and #:spec (and x y) #:impl (lambda v (andmap values v)) #:cost boolean-move-cost]
  [or  #:spec (or x y)  #:impl (lambda v (ormap values v))  #:cost boolean-move-cost])

(define-operation (not [x <bool>]) <bool>
  #:spec (not x) #:impl not #:cost boolean-move-cost)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;; BINARY32 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define-representation <binary32> #:cost 32bit-move-cost)

(define-operation (if.f32 [c <bool>] [t <binary32>] [f <binary32>]) <binary32>
  #:spec (if c t f) #:impl if-impl
  #:cost (if-cost boolean-move-cost))

(define-operations ([x <binary32>] [y <binary32>]) <bool>
  [==.f32 #:spec (== x y) #:impl =          #:cost 126.562475]
  [!=.f32 #:spec (!= x y) #:impl (negate =) #:cost 126.562475]
  [<.f32  #:spec (< x y)  #:impl <          #:cost 126.562475]
  [>.f32  #:spec (> x y)  #:impl >          #:cost 126.562475]
  [<=.f32 #:spec (<= x y) #:impl <=         #:cost 126.562475]
  [>=.f32 #:spec (>= x y) #:impl >=         #:cost 126.562475])

(define-operations () <binary32> #:fpcore (! :precision binary32 _)
  [PI.f32       #:spec (PI)       #:impl (const (flsingle pi)) #:fpcore PI       #:cost 32bit-move-cost]
  [E.f32        #:spec (E)        #:impl (const (flsingle (exp 1))) #:fpcore E        #:cost 32bit-move-cost]
  [INFINITY.f32 #:spec (INFINITY) #:impl (const +inf.0) #:fpcore INFINITY #:cost 32bit-move-cost]
  [NAN.f32      #:spec (NAN)      #:impl (const +nan.0) #:fpcore NAN      #:cost 32bit-move-cost])

(define-operation (neg.f32 [x <binary32>]) <binary32>
  #:spec (neg x) #:impl (compose flsingle -)
  #:fpcore (! :precision binary32 (- x)) #:cost 4.504403)

(define-operations ([x <binary32>] [y <binary32>]) <binary32> #:fpcore (! :precision binary32 _)
  [+.f32 #:spec (+ x y) #:impl (compose flsingle +) #:cost 113.232414]
  [-.f32 #:spec (- x y) #:impl (compose flsingle -) #:cost 117.04102]
  [*.f32 #:spec (* x y) #:impl (compose flsingle *) #:cost 114.843755]
  [/.f32 #:spec (/ x y) #:impl (compose flsingle /) #:cost 937.719687])

(define-operations ([x <binary32>]) <binary32> #:fpcore (! :precision binary32 _)
  [fabs.f32 #:spec (fabs x) #:impl (from-libm 'fabsf) #:cost 84.777838]
  [sin.f32 #:spec (sin x) #:impl (from-libm 'sinf) #:cost 2260.94962]
  [cos.f32 #:spec (cos x) #:impl (from-libm 'cosf) #:cost 2351.36722]
  [tan.f32 #:spec (tan x) #:impl (from-libm 'tanf) #:cost 2246.41117]
  [sinh.f32 #:spec (sinh x) #:impl (from-libm 'sinhf) #:cost 2836.34054]
  [cosh.f32 #:spec (cosh x) #:impl (from-libm 'coshf) #:cost 2220.19044]
  [tanh.f32 #:spec (tanh x) #:impl (from-libm 'tanhf) #:cost 1522.37544]
  [asin.f32 #:spec (asin x) #:impl (from-libm 'asinf) #:cost 1875.14661]
  [acos.f32 #:spec (acos x) #:impl (from-libm 'acosf) #:cost 2188.03716]
  [atan.f32 #:spec (atan x) #:impl (from-libm 'atanf) #:cost 1515.63718]
  [asinh.f32 #:spec (asinh x) #:impl (from-libm 'asinhf) #:cost 5909.47257]
  [acosh.f32 #:spec (acosh x) #:impl (from-libm 'acoshf) #:cost 3163.51334]
  [atanh.f32 #:spec (atanh x) #:impl (from-libm 'atanhf) #:cost 3046.10585]
  [cbrt.f32 #:spec (cbrt x) #:impl (from-libm 'cbrtf) #:cost 1997.82717]
  [ceil.f32 #:spec (ceil x) #:impl (from-libm 'ceilf) #:cost 106.71387]
  [floor.f32 #:spec (floor x) #:impl (from-libm 'floorf) #:cost 112.13379]
  [round.f32 #:spec (round x) #:impl (from-libm 'roundf) #:cost 699.133398]
  [rint.f32 #:spec (rint x) #:impl (from-libm 'rintf) #:cost 704.296917]
  [trunc.f32 #:spec (trunc x) #:impl (from-libm 'truncf) #:cost 105.102538]
  [erf.f32 #:spec (erf x) #:impl (from-libm 'erff) #:cost 1992.04101]
  [exp.f32 #:spec (exp x) #:impl (from-libm 'expf) #:cost 819.98287]
  [exp2.f32 #:spec (exp2 x) #:impl (from-libm 'exp2f) #:cost 699.316342]
  [lgamma.f32 #:spec (lgamma x) #:impl (from-libm 'lgammaf) #:cost 17698.0961]
  [log.f32 #:spec (log x) #:impl (from-libm 'logf) #:cost 1993.28615]
  [log10.f32 #:spec (log10 x) #:impl (from-libm 'log10f) #:cost 2110.51029]
  [log2.f32 #:spec (log2 x) #:impl (from-libm 'log2f) #:cost 2228.06402]
  [sqrt.f32 #:spec (sqrt x) #:impl (from-libm 'sqrtf) #:cost 940.173277]
  [tgamma.f32 #:spec (tgamma x) #:impl (from-libm 'tgammaf) #:cost 8904.49192])

(define-operations ([x <binary32>] [y <binary32>]) <binary32> #:fpcore (! :precision binary32 _)
  [pow.f32 #:spec (pow x y) #:impl (from-libm 'powf) #:cost 6557.29982]
  [atan2.f32 #:spec (atan2 x y) #:impl (from-libm 'atan2f) #:cost 3754.94392]
  [copysign.f32 #:spec (copysign x y) #:impl (from-libm 'copysignf) #:cost 107.629396]
  [fdim.f32 #:spec (fdim x y) #:impl (from-libm 'fdimf) #:cost 238.696282]
  [fmax.f32 #:spec (fmax x y) #:impl (from-libm 'fmaxf) #:cost 107.080083]
  [fmin.f32 #:spec (fmin x y) #:impl (from-libm 'fminf) #:cost 108.215329]
  [fmod.f32 #:spec (fmod x y) #:impl (from-libm 'fmodf) #:cost 936.218271]
  [remainder.f32 #:spec (remainder x y) #:impl (from-libm 'remainderf) #:cost 1636.99947])

(define-operations ([x <binary32>]) <binary32> #:fpcore (! :precision binary32 _)
  [erfc.f32 #:spec (- 1 (erf x)) #:impl (from-libm 'erfcf) #:fpcore (erfc x) #:cost 1992.04101]
  [expm1.f32 #:spec (- (exp x) 1) #:impl (from-libm 'expm1f) #:fpcore (expm1 x) #:cost 2461.08366]
  [log1p.f32 #:spec (log (+ 1 x)) #:impl (from-libm 'log1pf) #:fpcore (log1p x) #:cost 2220.92303])

(define-operation (hypot.f32 [x <binary32>] [y <binary32>]) <binary32>
  #:spec (sqrt (+ (* x x) (* y y))) #:impl (from-libm 'hypotf)
  #:fpcore (! :precision binary32 (hypot x y)) #:cost 2282.44653)

(define-operation (fma.f32 [x <binary32>] [y <binary32>] [z <binary32>]) <binary32>
  #:spec (+ (* x y) z) #:impl (from-libm 'fmaf)
  #:fpcore (! :precision binary32 (fma x y z)) #:cost 117.663592)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;; BINARY64 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define-representation <binary64> #:cost 64bit-move-cost)

(define-operation (if.f64 [c <bool>] [t <binary64>] [f <binary64>]) <binary64>
  #:spec (if c t f) #:impl if-impl
  #:cost (if-cost boolean-move-cost))

(define-operations ([x <binary64>] [y <binary64>]) <bool>
  [==.f64 #:spec (== x y) #:impl =          #:cost 6321.05675]
  [!=.f64 #:spec (!= x y) #:impl (negate =) #:cost 6321.05675]
  [<.f64  #:spec (< x y)  #:impl <          #:cost 6321.05675]
  [>.f64  #:spec (> x y)  #:impl >          #:cost 6321.05675]
  [<=.f64 #:spec (<= x y) #:impl <=         #:cost 6321.05675]
  [>=.f64 #:spec (>= x y) #:impl >=         #:cost 6321.05675])

(define-operations () <binary64> #:fpcore (! :precision binary64 _)
  [PI.f64       #:spec (PI)       #:impl (const pi) #:fpcore PI       #:cost 64bit-move-cost]
  [E.f64        #:spec (E)        #:impl (const (exp 1)) #:fpcore E        #:cost 64bit-move-cost]
  [INFINITY.f64 #:spec (INFINITY) #:impl (const +inf.0) #:fpcore INFINITY #:cost 64bit-move-cost]
  [NAN.f64      #:spec (NAN)      #:impl (const +nan.0) #:fpcore NAN      #:cost 64bit-move-cost])

(define-operation (neg.f64 [x <binary64>]) <binary64>
  #:spec (neg x) #:impl -
  #:fpcore (! :precision binary64 (- x)) #:cost 1e-06)

(define-operations ([x <binary64>] [y <binary64>]) <binary64> #:fpcore (! :precision binary64 _)
  [+.f64 #:spec (+ x y) #:impl + #:cost 51544.33456]
  [-.f64 #:spec (- x y) #:impl - #:cost 50062.50136]
  [*.f64 #:spec (* x y) #:impl * #:cost 50533.59056]
  [/.f64 #:spec (/ x y) #:impl / #:cost 363644.8176])

(define-operations ([x <binary64>]) <binary64> #:fpcore (! :precision binary64 _)
  [fabs.f64 #:spec (fabs x) #:impl (from-libm 'fabs) #:cost 233.679214]
  [sin.f64 #:spec (sin x) #:impl (from-libm 'sin) #:cost 109206.891]
  [cos.f64 #:spec (cos x) #:impl (from-libm 'cos) #:cost 109246.845]
  [tan.f64 #:spec (tan x) #:impl (from-libm 'tan) #:cost 185369.595]
  [sinh.f64 #:spec (sinh x) #:impl (from-libm 'sinh) #:cost 247740.821]
  [cosh.f64 #:spec (cosh x) #:impl (from-libm 'cosh) #:cost 12538.4027]
  [tanh.f64 #:spec (tanh x) #:impl (from-libm 'tanh) #:cost 87048.9981]
  [asin.f64 #:spec (asin x) #:impl (from-libm 'asin) #:cost 165859.528]
  [acos.f64 #:spec (acos x) #:impl (from-libm 'acos) #:cost 124297.774]
  [atan.f64 #:spec (atan x) #:impl (from-libm 'atan) #:cost 149994.891]
  [asinh.f64 #:spec (asinh x) #:impl (from-libm 'asinh) #:cost 243974.029]
  [acosh.f64 #:spec (acosh x) #:impl (from-libm 'acosh) #:cost 25220.2866]
  [atanh.f64 #:spec (atanh x) #:impl (from-libm 'atanh) #:cost 151199.091]
  [cbrt.f64 #:spec (cbrt x) #:impl (from-libm 'cbrt) #:cost 72618.0937]
  [ceil.f64 #:spec (ceil x) #:impl (from-libm 'ceil) #:cost 122.534175]
  [floor.f64 #:spec (floor x) #:impl (from-libm 'floor) #:cost 119.677725]
  [round.f64 #:spec (round x) #:impl (from-libm 'round) #:cost 12099.2063]
  [rint.f64 #:spec (rint x) #:impl (from-libm 'rint) #:cost 5353.78458]
  [trunc.f64 #:spec (trunc x) #:impl (from-libm 'trunc) #:cost 121.362325]
  [erf.f64 #:spec (erf x) #:impl (from-libm 'erf) #:cost 279785.797]
  [exp.f64 #:spec (exp x) #:impl (from-libm 'exp) #:cost 112681.871]
  [exp2.f64 #:spec (exp2 x) #:impl (from-libm 'exp2) #:cost 119004.663]
  [lgamma.f64 #:spec (lgamma x) #:impl (from-libm 'lgamma) #:cost 4560115.75]
  [log.f64 #:spec (log x) #:impl (from-libm 'log) #:cost 12555.0661]
  [log10.f64 #:spec (log10 x) #:impl (from-libm 'log10) #:cost 25116.3554]
  [log2.f64 #:spec (log2 x) #:impl (from-libm 'log2) #:cost 25138.7683]
  [sqrt.f64 #:spec (sqrt x) #:impl (from-libm 'sqrt) #:cost 378411.0424]
  [tgamma.f64 #:spec (tgamma x) #:impl (from-libm 'tgamma) #:cost 685167.289])

(define-operations ([x <binary64>] [y <binary64>]) <binary64> #:fpcore (! :precision binary64 _)
  [pow.f64 #:spec (pow x y) #:impl (from-libm 'pow) #:cost 512285.123]
  [atan2.f64 #:spec (atan2 x y) #:impl (from-libm 'atan2) #:cost 216025.655]
  [copysign.f64 #:spec (copysign x y) #:impl (from-libm 'copysign) #:cost 233.935589]
  [fdim.f64 #:spec (fdim x y) #:impl (from-libm 'fdim) #:cost 12559.973]
  [fmax.f64 #:spec (fmax x y) #:impl (from-libm 'fmax) #:cost 233.166531]
  [fmin.f64 #:spec (fmin x y) #:impl (from-libm 'fmin) #:cost 235.546861]
  [fmod.f64 #:spec (fmod x y) #:impl (from-libm 'fmod) #:cost 6331.6771]
  [remainder.f64 #:spec (remainder x y) #:impl (from-libm 'remainder) #:cost 31506.6267])

(define-operations ([x <binary64>]) <binary64> #:fpcore (! :precision binary64 _)
  [erfc.f64 #:spec (- 1 (erf x)) #:impl (from-libm 'erfc) #:fpcore (erfc x) #:cost 279785.797]
  [expm1.f64 #:spec (- (exp x) 1) #:impl (from-libm 'expm1) #:fpcore (expm1 x) #:cost 12530.5294]
  [log1p.f64 #:spec (log (+ 1 x)) #:impl (from-libm 'log1p) #:fpcore (log1p x) #:cost 132785.08])

(define-operation (hypot.f64 [x <binary64>] [y <binary64>]) <binary64>
  #:spec (sqrt (+ (* x x) (* y y))) #:impl (from-libm 'hypot)
  #:fpcore (! :precision binary64 (hypot x y)) #:cost 86978.0226)

(define-operation (fma.f64 [x <binary64>] [y <binary64>] [z <binary64>]) <binary64>
  #:spec (+ (* x y) z) #:impl (from-libm 'fma)
  #:fpcore (! :precision binary64 (fma x y z)) #:cost 50600.9732)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;; CASTS ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define-operation (binary32->binary64 [x <binary32>]) <binary64>
  #:spec x #:fpcore (! :precision binary64 (cast x)) #:impl identity #:cost 5717.41293)

(define-operation (binary64->binary32 [x <binary64>]) <binary32>
  #:spec x #:fpcore (! :precision binary32 (cast x)) #:impl flsingle #:cost 5730.12057)

)
