// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize %s | FileCheck %s

module {
  llvm.func @f(%x: f64, %y: f64) -> f64 {
    %0 = arith.mulf %x, %y : f64
    llvm.return %0 : f64
  }
  llvm.func @df(%x: f64, %dx: f64, %y: f64, %dy: f64) -> f64 {
    %res = enzyme.fwddiff @f(%x, %dx, %y, %dy) <{ activity=[#enzyme.activity<enzyme_dup>, #enzyme.activity<enzyme_dup>], ret_activity=[#enzyme.activity<enzyme_dup>] }> : (f64, f64, f64, f64) -> !llvm.struct<(f64, f64)>
    %p = llvm.extractvalue %res[0] : !llvm.struct<(f64, f64)>
    %t = llvm.extractvalue %res[1] : !llvm.struct<(f64, f64)>
    %s = arith.addf %p, %t : f64
    llvm.return %s : f64
  }
}

// CHECK-LABEL:   llvm.func @fwddiffef(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: f64,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: f64,
// CHECK-SAME:      %[[ARG2:[a-zA-Z0-9$._-]+]]: f64,
// CHECK-SAME:      %[[ARG3:[a-zA-Z0-9$._-]+]]: f64) -> !llvm.struct<(f64, f64)> attributes {sym_visibility = "private"} {
// CHECK:           %[[MLIR_0:.*]] = llvm.mlir.poison : !llvm.struct<(f64, f64)>
// CHECK:           %[[MULF_0:.*]] = arith.mulf %[[ARG1]], %[[ARG2]] fastmath<fast> : f64
// CHECK:           %[[MULF_1:.*]] = arith.mulf %[[ARG3]], %[[ARG0]] fastmath<fast> : f64
// CHECK:           %[[ADDF_0:.*]] = arith.addf %[[MULF_0]], %[[MULF_1]] fastmath<fast> : f64
// CHECK:           %[[MULF_2:.*]] = arith.mulf %[[ARG0]], %[[ARG2]] : f64
// CHECK:           %[[INSERTVALUE_0:.*]] = llvm.insertvalue %[[MULF_2]], %[[MLIR_0]][0] : !llvm.struct<(f64, f64)>
// CHECK:           %[[INSERTVALUE_1:.*]] = llvm.insertvalue %[[ADDF_0]], %[[INSERTVALUE_0]][1] : !llvm.struct<(f64, f64)>
// CHECK:           llvm.return %[[INSERTVALUE_1]] : !llvm.struct<(f64, f64)>
// CHECK:         }
