//===- LowerLLVMExtPass.cpp - Lower LLVM Ext operations  ------------------ //
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file implements a pass to lower custom ops generated by the LLVM Ext
// dialect.
//
//===----------------------------------------------------------------------===//

#include "Dialect/LLVMExt/LLVMExt.h"
#include "Passes/Passes.h"

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"

#include "mlir/IR/Dominance.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Interfaces/ViewLikeInterface.h"

namespace mlir {
namespace enzyme {
using namespace mlir::enzyme;
#define GEN_PASS_DEF_LOWERLLVMEXTPASS
#include "Passes/Passes.h.inc"
} // namespace enzyme
} // namespace mlir

namespace {
using namespace mlir;
using namespace enzyme;

LogicalResult tryLoweringToAlloca(llvm_ext::AllocOp alloc,
                                  uint64_t staticThreshold) {
  llvm::APInt size;
  if (!matchPattern(alloc.getSize(), m_ConstantInt(&size)))
    return failure();

  if (size.getZExtValue() > staticThreshold)
    return failure();

  Operation *free = nullptr;
  for (auto user : alloc.getResult().getUsers()) {
    auto oFree = dyn_cast<llvm_ext::FreeOp>(user);
    if (!oFree)
      continue;

    if (free)
      return failure(); // multiple frees

    if (oFree->getBlock() != alloc->getBlock()) // free not in same block
      return failure();

    free = user;

    if (!alloc->isBeforeInBlock(free))
      return failure();
  }

  OpBuilder builder(alloc);
  auto alloca = LLVM::AllocaOp::create(builder, alloc.getLoc(),
                                       alloc.getResult().getType(),
                                       builder.getI8Type(), alloc.getSize());
  alloc.getResult().replaceAllUsesWith(alloca.getResult());

  LLVM::LifetimeStartOp::create(builder, alloc.getLoc(), alloca.getResult());

  builder.setInsertionPoint(free);
  LLVM::LifetimeEndOp::create(builder, alloc.getLoc(), alloca.getResult());

  free->erase();
  alloc->erase();

  return success();
}

void lowerAlloc(llvm_ext::AllocOp alloc, uint64_t staticThreshold) {
  if (tryLoweringToAlloca(alloc, staticThreshold).succeeded())
    return;

  SymbolTable symtable(SymbolTable::getNearestSymbolTable(alloc));

  auto mallocFn = symtable.lookup<LLVM::LLVMFuncOp>("malloc");
  if (!mallocFn) {
    Block *b = &symtable.getOp()->getRegion(0).front();
    OpBuilder builder(b, b->begin());

    auto fnType = mlir::LLVM::LLVMFunctionType::get(
        LLVM::LLVMPointerType::get(alloc.getContext()), builder.getI64Type(),
        /*isVarArg=*/false);

    mallocFn =
        LLVM::LLVMFuncOp::create(builder, alloc.getLoc(), "malloc", fnType);
  }

  OpBuilder builder(alloc);
  auto mallocCall = LLVM::CallOp::create(builder, alloc.getLoc(), mallocFn,
                                         alloc->getOperands());
  alloc.getResult().replaceAllUsesWith(mallocCall.getResult());
  alloc.erase();
}

void lowerFree(llvm_ext::FreeOp free) {
  SymbolTable symtable(SymbolTable::getNearestSymbolTable(free));

  auto freeFn = symtable.lookup<LLVM::LLVMFuncOp>("free");
  if (!freeFn) {
    Block *b = &symtable.getOp()->getRegion(0).front();
    OpBuilder builder(b, b->begin());

    auto fnType = mlir::LLVM::LLVMFunctionType::get(
        LLVM::LLVMVoidType::get(free.getContext()),
        LLVM::LLVMPointerType::get(free.getContext()),
        /*isVarArg=*/false);

    freeFn = LLVM::LLVMFuncOp::create(builder, free.getLoc(), "free", fnType);
  }

  OpBuilder builder(free);
  LLVM::CallOp::create(builder, free.getLoc(), freeFn, free->getOperands());

  free.erase();
}

/// `llvm_ext.ptr_size_hint` is the only record of how large a raw pointer's
/// allocation is, and this pass drops it. Reverse-mode AD recovers the extent of
/// a pointer-derived memref with `memref.dim` (see
/// MemRefClonableTypeInterface::cloneValue) -- e.g. to size the checkpoint
/// buffer for a cached grid -- but a `memref.dim` of a value that is really just
/// a bare pointer has no lowering at all: the size is nowhere in the IR once the
/// hint is gone. Resolve those dims from the hint while it is still around.
static void resolveDimsFromHint(llvm_ext::PtrSizeHintOp psh,
                                DominanceInfo &dom) {
  Value ptr = psh.getPtr();
  Value byteSize = psh.getSize();

  for (Operation *user : llvm::make_early_inc_range(ptr.getUsers())) {
    // A side-effect-free view of the pointer as a rank-1 dynamic memref is a
    // reinterpret cast, so the pointee's byte size fixes the memref's extent.
    auto view = dyn_cast<ViewLikeOpInterface>(user);
    if (!view || view.getViewSource() != ptr || !isMemoryEffectFree(user))
      continue;
    auto MT = dyn_cast<MemRefType>(user->getResult(0).getType());
    if (!MT || MT.getRank() != 1 || !MT.isDynamicDim(0))
      continue;
    if (!MT.getElementType().isIntOrFloat())
      continue;
    unsigned bits = MT.getElementTypeBitWidth();
    if (bits == 0 || bits % 8 != 0)
      continue;

    for (Operation *dimUser :
         llvm::make_early_inc_range(user->getResult(0).getUsers())) {
      auto dim = dyn_cast<memref::DimOp>(dimUser);
      if (!dim || dim.getConstantIndex() != 0)
        continue;
      // The hint's size operand has to be available where the dim was.
      if (!dom.properlyDominates(byteSize, dim))
        continue;

      OpBuilder builder(dim);
      Value extent = arith::IndexCastOp::create(
          builder, dim.getLoc(), builder.getIndexType(), byteSize);
      if (unsigned bytes = bits / 8; bytes != 1) {
        Value elemSize =
            arith::ConstantIndexOp::create(builder, dim.getLoc(), bytes);
        extent =
            arith::DivUIOp::create(builder, dim.getLoc(), extent, elemSize);
      }
      dim.getResult().replaceAllUsesWith(extent);
      dim.erase();
    }
  }
}

struct LowerLLVMExtPass
    : public enzyme::impl::LowerLLVMExtPassBase<LowerLLVMExtPass> {
  using LowerLLVMExtPassBase::LowerLLVMExtPassBase;

  void runOnOperation() override {
    Operation *op = getOperation();

    DominanceInfo dom(op);
    op->walk([&](llvm_ext::PtrSizeHintOp psh) {
      resolveDimsFromHint(psh, dom);
      psh.erase();
    });

    SmallVector<llvm_ext::AllocOp> allocs;
    op->walk([&](llvm_ext::AllocOp alloc) { allocs.push_back(alloc); });

    for (auto alloc : allocs)
      lowerAlloc(alloc, lowerToAllocaThreshold);

    SmallVector<llvm_ext::FreeOp> frees;
    op->walk([&](llvm_ext::FreeOp free) { frees.push_back(free); });

    for (auto free : frees)
      lowerFree(free);
  }
};

} // end anonymous namespace
