[package]
name = "enzyme"
version = "0.4.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-Exceptions"
authors = [
	"Manuel Drehwald",
	"Lorenz Schmidt"
]
repository = "https://github.com/EnzymeAD/Enzyme"
keywords = ["enzyme", "auto-diff", "llvm", "machine-learning", "scientific-computing"]
categories = ["development-tools::cargo-plugins", "mathematics", "science", "simulation"]
readme = "README.md"
documentation = "https://docs.rs/enzyme/"
homepage = "https://enzyme.mit.edu"
description = "A helper crate to simplify experimenting with Enzyme."


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "enzyme-install"
path = "src/bin/main.rs"

[[bin]]
name = "cargo-enzyme"
path = "src/bin/run.rs"

[dependencies]
clap = { version = "3.1", features = ["default", "derive"] }
bindgen = { version = "0.58", default-features = false }
dirs = { version = "3.0", default-features = false }
curl = "0.4"
tar = { version = "0.4", default-features = false }
flate2 = "1.0"
