; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --include-generated-funcs
; RUN: %opt < %s %loadEnzyme -enzyme -enzyme-preopt=false -enzyme-vectorize-at-leaf-nodes -mem2reg -simplifycfg -adce -instsimplify -S | FileCheck %s

; Function Attrs: nounwind
declare <2 x double> @__enzyme_fwddiff(double (float)*, ...)

define double @tester(float %x) {
entry:
  %y = fpext float %x to double
  ret double %y
}

define <2 x double> @test_derivative(float %x) {
entry:
  %0 = tail call <2 x double> (double (float)*, ...) @__enzyme_fwddiff(double (float)* nonnull @tester,  metadata !"enzyme_width", i64 2, float %x, <2 x float> <float 1.0, float 2.0>)
  ret <2 x double> %0
}


; CHECK: define internal <2 x double> @fwddiffe2tester(float %x, <2 x float> %"x'")
; CHECK-NEXT:  entry:
; CHECK-NEXT:   %"y'ipc" = fpext <2 x float> %"x'" to <2 x double>
; CHECK-NEXT:   ret <2 x double> %"y'ipc"
; CHECK-NEXT: }