; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --include-generated-funcs
; RUN: %opt < %s %loadEnzyme -enzyme -enzyme-preopt=false -enzyme-vectorize-at-leaf-nodes -mem2reg -instsimplify -adce -correlated-propagation -simplifycfg -adce -S | FileCheck %s

; Function Attrs: nounwind
declare void @__enzyme_fwddiff(void (float*, float*)*, ...)

define dso_local void @sum(float* %array, float* %ret) #4 {
entry:
  br label %do.body

do.body:                                          ; preds = %do.body, %entry
  %i = phi i64 [ %inc, %do.body ], [ 0, %entry ]
  %intsum = phi i32 [ 0, %entry ], [ %intadd, %do.body ]
  %arrayidx = getelementptr inbounds float, float* %array, i64 %i
  %loaded = load float, float* %arrayidx
  %fltload = bitcast i32 %intsum to float
  %add = fadd float %fltload, %loaded
  %intadd = bitcast float %add to i32
  %inc = add nuw nsw i64 %i, 1
  %cmp = icmp eq i64 %inc, 5
  br i1 %cmp, label %do.end, label %do.body

do.end:                                           ; preds = %do.body
  %lcssa = phi float [ %add, %do.body ]
  store float %lcssa, float* %ret, align 4
  ret void
}

; Function Attrs: nounwind uwtable
define dso_local void @dsum(float* %x, <3 x float>* %xp, float* %n, <3 x float>* %np) local_unnamed_addr #1 {
entry:
  tail call void (void (float*, float*)*, ...) @__enzyme_fwddiff(void (float*, float*)* nonnull @sum, metadata !"enzyme_width", i64 3, float* %x, <3 x float>* %xp, float* %n, <3 x float>* %np)
  ret void
}


; CHECK: define internal void @fwddiffe3sum(float* %array, <3 x float>* %"array'", float* %ret, <3 x float>* %"ret'")
; CHECK-NEXT: entry:
; CHECK-NEXT:   br label %do.body

; CHECK: do.body:                                          ; preds = %do.body, %entry
; CHECK-NEXT:   %iv = phi i64 [ %iv.next, %do.body ], [ 0, %entry ]
; CHECK-NEXT:   %0 = phi <3 x i32> [ zeroinitializer, %entry ], [ %"intadd'ipc", %do.body ]
; CHECK-NEXT:   %intsum = phi i32 [ 0, %entry ], [ %intadd, %do.body ]
; CHECK-NEXT:   %iv.next = add nuw nsw i64 %iv, 1
; CHECK-NEXT:   %"arrayidx'ipg" = getelementptr inbounds <3 x float>, <3 x float>* %"array'", i64 %iv
; CHECK-NEXT:   %arrayidx = getelementptr inbounds float, float* %array, i64 %iv
; CHECK-NEXT:   %"loaded'ipl" = load <3 x float>, <3 x float>* %"arrayidx'ipg", align 4
; CHECK-NEXT:   %loaded = load float, float* %arrayidx, align 4
; CHECK-NEXT:   %"fltload'ipc" = bitcast <3 x i32> %0 to <3 x float>
; CHECK-NEXT:   %fltload = bitcast i32 %intsum to float
; CHECK-NEXT:   %add = fadd float %fltload, %loaded
; CHECK-NEXT:   %1 = fadd fast <3 x float> %"fltload'ipc", %"loaded'ipl"
; CHECK-NEXT:   %"intadd'ipc" = bitcast <3 x float> %1 to <3 x i32>
; CHECK-NEXT:   %intadd = bitcast float %add to i32
; CHECK-NEXT:   %cmp = icmp eq i64 %iv.next, 5
; CHECK-NEXT:   br i1 %cmp, label %do.end, label %do.body

; CHECK: do.end:                                           ; preds = %do.body
; CHECK-NEXT:   store float %add, float* %ret, align 4
; CHECK-NEXT:   store <3 x float> %1, <3 x float>* %"ret'", align 4
; CHECK-NEXT:   ret void
; CHECK-NEXT: }
