name: Build and deploy Doxygen to Scripts

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mattnotmitt/doxygen-action@v1.12.0
        with:
          working-directory: 'enzyme/'
          doxyfile-path: 'doxygen.cfg'

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: enzyme/doxygen/html
          
  deploy-docs:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
