name: Mac Enzyme CI

on: [push]

jobs:
  build:
    name: Enzyme CI LLVM ${{ matrix.llvm }} ${{ matrix.build }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        llvm: ["7", "8", "9", "11"]
        build: ["Release", "Debug"] # "RelWithDebInfo"
        os: [macos-11.0, macos-10.15] #self-hosted]
    
    timeout-minutes: 30 
    steps:
    - name: add llvm 
      run: |
          #sudo apt-get remove  -y llvm-${{ matrix.llvm }}-dev llvm-${{ matrix.llvm }}-tools 
          brew install llvm@${{ matrix.llvm }} autoconf cmake gcc
          sudo pip3 install lit
    - uses: actions/checkout@v2
      with:
          fetch-depth: 1
    - name: mkdir
      run: cd enzyme && rm -rf build && mkdir build
    - name: cmake
      run: |
          cd enzyme/build 
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DLLVM_EXTERNAL_LIT=`which lit` -DLLVM_DIR=/usr/local/opt/llvm@${{ matrix.llvm }}/lib/cmake/llvm
    - name: make
      run: cd enzyme/build && make -j`sysctl -n hw.logicalcpu`
    - name: make check-typeanalysis
      run: cd enzyme/build && make check-typeanalysis -j`sysctl -n hw.logicalcpu`
    - name: make check-enzyme
      run: cd enzyme/build && make check-enzyme -j`sysctl -n hw.logicalcpu`
