name: Enzyme Rust CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  rust-autodiff:
    name: Rust Autodiff ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [linux-x86-n2-32]
    
    timeout-minutes: 90

    container:
      image: ${{ (contains(matrix.os, 'linux') && 'ghcr.io/enzymead/reactant-docker-images@sha256:91e1edb7a7c869d5a70db06e417f22907be0e67ca86641d48adcea221fedc674' ) || '' }}
    
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y binutils ninja-build cmake gcc g++ python3 python3-dev ccache nodejs npm
    - name: Install Rust toolchain
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        . ~/.cargo/env
        rustup toolchain install nightly-2025-09-01
        rustup default nightly
    - uses: actions/checkout@v4
      name: Checkout Enzyme
    - name: Set BASE_DIR
      run: |
        BASE_DIR=${GITHUB_WORKSPACE}
        echo "BASE_DIR=${BASE_DIR}" >> ${GITHUB_ENV}
    - name: Clone and configure Rust compiler
      run: |
        . ~/.cargo/env
        git clone --depth 1 --branch master https://github.com/rust-lang/rust.git
        cd rust
        ./configure --enable-llvm-link-shared --enable-llvm-plugins --enable-llvm-enzyme --release-channel=nightly --enable-llvm-assertions --enable-clang --enable-lld --enable-option-checking --enable-ninja --disable-docs --enable-ccache
    - name: Cache Rust build
      uses: actions/cache@v4
      with:
        path: |
          rust/build
          ~/.cargo/registry
          ~/.cargo/git
          ~/.ccache
        key: rust-${{ matrix.os }}-${{ hashFiles('rust/.git/HEAD') }}
        restore-keys: |
          rust-${{ matrix.os }}-
    - name: Build Rust compiler stage 1
      working-directory: rust
      run: |
        . ~/.cargo/env
        ./x build --stage 1 library
    - name: Build Enzyme with Rust's LLVM
      run: |
        . ~/.cargo/env
        rm -rf build && mkdir build && cd build
        cmake ../enzyme -DCMAKE_BUILD_TYPE=Release -DLLVM_DIR=${{ env.BASE_DIR }}/rust/build/x86_64-unknown-linux-gnu/llvm/lib/cmake/llvm
        make -j `nproc`
    - name: Run Rust autodiff tests
      working-directory: rust
      run: |
        source ~/.cargo/env
        ./x test --stage 1 tests/codegen-llvm/autodiff
        ./x test --stage 1 tests/pretty/autodiff
        ./x test --stage 1 tests/ui/autodiff
        ./x test --stage 1 tests/ui/feature-gates/feature-gate-autodiff.rs
