name: Clang-Format

on:
  push:
  pull_request:
  merge_group:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
   
jobs:
  build:
    name: Format
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Enzyme repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: 'enzyme/Enzyme enzyme/tools/enzyme-tblgen'
        exclude: './CMakeLists.txt enzyme/Enzyme/SCEV'
        style: 'llvm'
        clangFormatVersion: 16
