name: Julia CI

on: [push]

jobs:
  test:
    name: Test on os ${{ matrix.os }} and Julia ${{ matrix.julia-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.4', 'nightly']
        os: [self-hosted]
    
    timeout-minutes: 30 
    steps:
      - name: "Checkout Enzyme code"
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: "Cleanup"
        run: |
          rm -rf ${HOME}/julia
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: "Download LLVM & build Ennzyme"
        run: |
          LLVM_MAJOR_VER=`julia -e "print(Base.libllvm_version.major)"`
          julia -e "using Pkg; pkg\"add LLVM_full_jll@${LLVM_MAJOR_VER}\""
          LLVM_DIR=`julia -e "using LLVM_full_jll; print(LLVM_full_jll.artifact_dir)"`
          echo "LLVM_DIR=$LLVM_DIR"
          mkdir build
          cd build
          cmake --version
          cmake -DLLVM_DIR=${LLVM_DIR} \
                -DLLVM_EXTERNAL_LIT=${LLVM_DIR}/tools/lit/lit.py ../enzyme
          make -j
        env:
          JULIA_PROJECT: "/tmp/proj"
      - name: "Julia tests"
        run: |
          cd build
          make check-enzyme-julia
