name: Tag CI

on: [release]

jobs:
  build:
    name: Enzyme Tag CI
    runs-on: ubuntu-latest
    steps:
    - uses: tibdex/github-app-token@v1
      id: generate_token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
        repository: JuliaPackaging/Yggdrasil

    - uses: actions/checkout@v2
      with:
          repository: 'JuliaPackaging/Yggdrasil'
          fetch-depth: 1
          path: ygg

    - uses: actions/checkout@v2
      with:
          fetch-depth: 1
          path: enz
    - name: replace
      run: |
          cd ygg
          git rm -rf E/Enzyme
          mkdir -p E/Enzyme/Enzyme@9
          cd E/Enzyme
          cp ../../../enz/.packaging/build_tarballs.jl Enzyme@9/build_tarballs.jl
          sed "s~%ENZYME_VERSION%~${GITHUB_REF}~g" Enzyme@9/build_tarballs.jl -i
          sed "s~%ENZYME_HASH%~${GITHUB_SHA}~g" Enzyme@9/build_tarballs.jl -i
          git add Enzyme@9
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        path: ygg
        commit-message: "Upgrade enzyme to ${{ github.ref }}"
        title: "Upgrade enzyme to ${{ github.ref }}"
        token: ${{ steps.generate_token.outputs.token }}
        reviewers: vchuravy
        branch: enzyme/${{ github.ref }}
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
